version: '3'

services:

  java-native-utils-test-armel:
    platform: "linux/arm/v5"
    build:
      context: image
    container_name: java-native-utils-test-armel
    environment:
      - QEMU=true
      - QARCH=armel
    volumes:
      - ../../../:/project
    entrypoint: /usr/bin/env bash /project/JavaNativeUtilsTest/docker/runtest.sh


