/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil */

#ifndef _Included_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
#define _Included_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    getFD
 * Signature: (Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_getFD
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    to_struct_timeval
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_to_1struct_1timeval
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    from_struct_timeval
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_from_1struct_1timeval
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    to_sockaddr_in
 * Signature: (Ljava/net/InetSocketAddress;)Lio/github/alexanderschuetz97/nativeutils/api/structs/Sockaddr;
 */
JNIEXPORT jobject JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_to_1sockaddr_1in
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    from_sockaddr_in
 * Signature: (Lio/github/alexanderschuetz97/nativeutils/api/structs/Sockaddr;)Ljava/net/InetSocketAddress;
 */
JNIEXPORT jobject JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_from_1sockaddr_1in
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    to_sockaddr_un
 * Signature: (Ljava/lang/String;)Lio/github/alexanderschuetz97/nativeutils/api/structs/Sockaddr;
 */
JNIEXPORT jobject JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_to_1sockaddr_1un
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    from_sockaddr_un
 * Signature: (Lio/github/alexanderschuetz97/nativeutils/api/structs/Sockaddr;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_from_1sockaddr_1un
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    socket
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_socket
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    poll
 * Signature: ([Lio/github/alexanderschuetz97/nativeutils/api/structs/PollFD;I)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_poll
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_read
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_write
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    recvfrom
 * Signature: (I[BIIILio/github/alexanderschuetz97/nativeutils/api/structs/Sockaddr;)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_recvfrom
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint, jobject);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    connect
 * Signature: (ILio/github/alexanderschuetz97/nativeutils/api/structs/Sockaddr;)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_connect
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    getsockopt
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_getsockopt__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    getsockopt
 * Signature: (IIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_getsockopt__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    setsockopt
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_setsockopt__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    setsockopt
 * Signature: (III[B)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_setsockopt__III_3B
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    fnctl_F_SETLK
 * Signature: (ILio/github/alexanderschuetz97/nativeutils/api/LinuxNativeUtil/fnctl_F_SETLK_Mode;JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_fnctl_1F_1SETLK
  (JNIEnv *, jobject, jint, jobject, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    fnctl_F_SETLKW
 * Signature: (ILio/github/alexanderschuetz97/nativeutils/api/LinuxNativeUtil/fnctl_F_SETLK_Mode;JJ)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_fnctl_1F_1SETLKW
  (JNIEnv *, jobject, jint, jobject, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    fnctl_F_GETLK
 * Signature: (IZJJ)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_fnctl_1F_1GETLK
  (JNIEnv *, jobject, jint, jboolean, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    chdir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_chdir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    symlink
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_symlink
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    link
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_link
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    stat
 * Signature: (Ljava/lang/String;)Lio/github/alexanderschuetz97/nativeutils/api/structs/Stat;
 */
JNIEXPORT jobject JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_stat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    fstat
 * Signature: (I)Lio/github/alexanderschuetz97/nativeutils/api/structs/Stat;
 */
JNIEXPORT jobject JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_fstat
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    strerror_r
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_strerror_1r
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil
 * Method:    lstat
 * Signature: (Ljava/lang/String;)Lio/github/alexanderschuetz97/nativeutils/api/structs/Stat;
 */
JNIEXPORT jobject JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNILinuxNativeUtil_lstat
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
