/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_alexanderschuetz97_nativeutils_impl_NativeLibraryLoaderHelper */

#ifndef _Included_io_github_alexanderschuetz97_nativeutils_impl_NativeLibraryLoaderHelper
#define _Included_io_github_alexanderschuetz97_nativeutils_impl_NativeLibraryLoaderHelper
#ifdef __cplusplus
extern "C" {
#endif
#undef io_github_alexanderschuetz97_nativeutils_impl_NativeLibraryLoaderHelper_EXPECTED_NATIVE_LIB_VERSION
#define io_github_alexanderschuetz97_nativeutils_impl_NativeLibraryLoaderHelper_EXPECTED_NATIVE_LIB_VERSION 4L
/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_NativeLibraryLoaderHelper
 * Method:    getNativeLibVersion
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_NativeLibraryLoaderHelper_getNativeLibVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
