/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil */

#ifndef _Included_io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil
#define _Included_io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil
 * Method:    _FromReflectedField
 * Signature: (Ljava/lang/reflect/Field;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil__1FromReflectedField
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil
 * Method:    _ToReflectedField
 * Signature: (Ljava/lang/Class;JZ)Ljava/lang/reflect/Field;
 */
JNIEXPORT jobject JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil__1ToReflectedField
  (JNIEnv *, jobject, jclass, jlong, jboolean);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil
 * Method:    _GetFieldID
 * Signature: (Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil__1GetFieldID
  (JNIEnv *, jobject, jclass, jstring, jstring);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil
 * Method:    _GetStaticFieldID
 * Signature: (Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil__1GetStaticFieldID
  (JNIEnv *, jobject, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
