/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod */

#ifndef _Included_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
#define _Included_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _NewObject
 * Signature: (Ljava/lang/Class;J[I[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1NewObject
  (JNIEnv *, jclass, jclass, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallObjectMethod
 * Signature: (Ljava/lang/Object;J[I[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallObjectMethod
  (JNIEnv *, jclass, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallVoidMethod
 * Signature: (Ljava/lang/Object;J[I[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallVoidMethod
  (JNIEnv *, jclass, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallLongMethod
 * Signature: (Ljava/lang/Object;J[I[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallLongMethod
  (JNIEnv *, jclass, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallIntMethod
 * Signature: (Ljava/lang/Object;J[I[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallIntMethod
  (JNIEnv *, jclass, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallShortMethod
 * Signature: (Ljava/lang/Object;J[I[Ljava/lang/Object;)S
 */
JNIEXPORT jshort JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallShortMethod
  (JNIEnv *, jclass, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallCharMethod
 * Signature: (Ljava/lang/Object;J[I[Ljava/lang/Object;)C
 */
JNIEXPORT jchar JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallCharMethod
  (JNIEnv *, jclass, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallByteMethod
 * Signature: (Ljava/lang/Object;J[I[Ljava/lang/Object;)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallByteMethod
  (JNIEnv *, jclass, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallBooleanMethod
 * Signature: (Ljava/lang/Object;J[I[Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallBooleanMethod
  (JNIEnv *, jclass, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallFloatMethod
 * Signature: (Ljava/lang/Object;J[I[Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallFloatMethod
  (JNIEnv *, jclass, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallDoubleMethod
 * Signature: (Ljava/lang/Object;J[I[Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallDoubleMethod
  (JNIEnv *, jclass, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallStaticObjectMethod
 * Signature: (Ljava/lang/Class;J[I[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallStaticObjectMethod
  (JNIEnv *, jclass, jclass, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallStaticVoidMethod
 * Signature: (Ljava/lang/Class;J[I[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallStaticVoidMethod
  (JNIEnv *, jclass, jclass, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallStaticLongMethod
 * Signature: (Ljava/lang/Class;J[I[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallStaticLongMethod
  (JNIEnv *, jclass, jclass, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallStaticIntMethod
 * Signature: (Ljava/lang/Class;J[I[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallStaticIntMethod
  (JNIEnv *, jclass, jclass, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallStaticShortMethod
 * Signature: (Ljava/lang/Class;J[I[Ljava/lang/Object;)S
 */
JNIEXPORT jshort JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallStaticShortMethod
  (JNIEnv *, jclass, jclass, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallStaticByteMethod
 * Signature: (Ljava/lang/Class;J[I[Ljava/lang/Object;)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallStaticByteMethod
  (JNIEnv *, jclass, jclass, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallStaticCharMethod
 * Signature: (Ljava/lang/Class;J[I[Ljava/lang/Object;)C
 */
JNIEXPORT jchar JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallStaticCharMethod
  (JNIEnv *, jclass, jclass, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallStaticBooleanMethod
 * Signature: (Ljava/lang/Class;J[I[Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallStaticBooleanMethod
  (JNIEnv *, jclass, jclass, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallStaticFloatMethod
 * Signature: (Ljava/lang/Class;J[I[Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallStaticFloatMethod
  (JNIEnv *, jclass, jclass, jlong, jintArray, jobjectArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod
 * Method:    _CallStaticDoubleMethod
 * Signature: (Ljava/lang/Class;J[I[Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMethod__1CallStaticDoubleMethod
  (JNIEnv *, jclass, jclass, jlong, jintArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
