/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory */

#ifndef _Included_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
#define _Included_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    atomic8ByteOperationsRequireAlignment
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_atomic8ByteOperationsRequireAlignment
  (JNIEnv *, jobject);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    writeExpandedByteArray
 * Signature: (JJ[BIII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_writeExpandedByteArray
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readExpandedByteArray
 * Signature: (JJ[BIII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readExpandedByteArray
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    writeExpandedCharArray
 * Signature: (JJ[CIII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_writeExpandedCharArray
  (JNIEnv *, jclass, jlong, jlong, jcharArray, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readExpandedCharArray
 * Signature: (JJ[CIII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readExpandedCharArray
  (JNIEnv *, jclass, jlong, jlong, jcharArray, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    writeExpandedShortArray
 * Signature: (JJ[SIII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_writeExpandedShortArray
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readExpandedShortArray
 * Signature: (JJ[SIII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readExpandedShortArray
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    writeExpandedIntArray
 * Signature: (JJ[IIII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_writeExpandedIntArray
  (JNIEnv *, jclass, jlong, jlong, jintArray, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readExpandedIntArray
 * Signature: (JJ[IIII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readExpandedIntArray
  (JNIEnv *, jclass, jlong, jlong, jintArray, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    writeExpandedLongArray
 * Signature: (JJ[JIII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_writeExpandedLongArray
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readExpandedLongArray
 * Signature: (JJ[JIII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readExpandedLongArray
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jint, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    writeFloatArray
 * Signature: (JJ[FII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_writeFloatArray
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readFloatArray
 * Signature: (JJ[FII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readFloatArray
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    writeDoubleArray
 * Signature: (JJ[DII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_writeDoubleArray
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readDoubleArray
 * Signature: (JJ[DII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readDoubleArray
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    supportsAtomicOperations
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_supportsAtomicOperations
  (JNIEnv *, jobject);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    supports16ByteCompareAndSet
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_supports16ByteCompareAndSet
  (JNIEnv *, jobject);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readUntilByte
 * Signature: (JJIB[BI)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readUntilByte
  (JNIEnv *, jclass, jlong, jlong, jint, jbyte, jbyteArray, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    indexOf
 * Signature: (JJJB)J
 */
JNIEXPORT jlong JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_indexOf
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyte);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    off
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_off
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJ[BII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_write__JJ_3BII
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJB)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_write__JJB
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_write__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_write__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_write__JJF
  (JNIEnv *, jclass, jlong, jlong, jfloat);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_write__JJD
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJS)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_write__JJS
  (JNIEnv *, jclass, jlong, jlong, jshort);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    read
 * Signature: (JJ[BII)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_read
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readInt
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readInt
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readLong
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readFloat
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readFloat
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readDouble
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readShort
 * Signature: (JJ)S
 */
JNIEXPORT jshort JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readShort
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readByte
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readByte
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    set
 * Signature: (JJBJ)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_set
  (JNIEnv *, jclass, jlong, jlong, jbyte, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    getAndAdd
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_getAndAdd__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    getAndAdd
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_getAndAdd__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    getAndAdd
 * Signature: (JJS)S
 */
JNIEXPORT jshort JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_getAndAdd__JJS
  (JNIEnv *, jclass, jlong, jlong, jshort);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    getAndAdd
 * Signature: (JJB)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_getAndAdd__JJB
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    getAndSet
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_getAndSet__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    getAndSet
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_getAndSet__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    getAndSet
 * Signature: (JJS)S
 */
JNIEXPORT jshort JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_getAndSet__JJS
  (JNIEnv *, jclass, jlong, jlong, jshort);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    getAndSet
 * Signature: (JJB)B
 */
JNIEXPORT jbyte JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_getAndSet__JJB
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_compareAndSet__JJJJ
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet
 * Signature: (JJII)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_compareAndSet__JJII
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet
 * Signature: (JJSS)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_compareAndSet__JJSS
  (JNIEnv *, jclass, jlong, jlong, jshort, jshort);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet
 * Signature: (JJBB)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_compareAndSet__JJBB
  (JNIEnv *, jclass, jlong, jlong, jbyte, jbyte);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet
 * Signature: (JJ[B)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_compareAndSet__JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJJJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spinAndSet__JJJJJJ
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJJJJ)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spinAndSet__JJJJJ
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spin__JJJJJ
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spin__JJJJ
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJIIJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spinAndSet__JJIIJJ
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJIIJ)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spinAndSet__JJIIJ
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJIJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spin__JJIJJ
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJIJ)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spin__JJIJ
  (JNIEnv *, jobject, jlong, jlong, jint, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJSSJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spinAndSet__JJSSJJ
  (JNIEnv *, jobject, jlong, jlong, jshort, jshort, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJSSJ)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spinAndSet__JJSSJ
  (JNIEnv *, jobject, jlong, jlong, jshort, jshort, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJSJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spin__JJSJJ
  (JNIEnv *, jobject, jlong, jlong, jshort, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJSJ)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spin__JJSJ
  (JNIEnv *, jobject, jlong, jlong, jshort, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJBBJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spinAndSet__JJBBJJ
  (JNIEnv *, jobject, jlong, jlong, jbyte, jbyte, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJBBJ)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spinAndSet__JJBBJ
  (JNIEnv *, jobject, jlong, jlong, jbyte, jbyte, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJBJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spin__JJBJJ
  (JNIEnv *, jobject, jlong, jlong, jbyte, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJBJ)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_spin__JJBJ
  (JNIEnv *, jobject, jlong, jlong, jbyte, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    memmove
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_memmove
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    readBuffer
 * Signature: (JJLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_readBuffer
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint);

/*
 * Class:     io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory
 * Method:    writeBuffer
 * Signature: (JJLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_io_github_alexanderschuetz97_nativeutils_impl_JNINativeMemory_writeBuffer
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
