/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil_BufferPointerHandler */

#ifndef _Included_io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil_BufferPointerHandler
#define _Included_io_github_alexanderschuetz97_nativeutils_impl_JNICommonNativeUtil_BufferPointerHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
