version: '3'

services:

  java-native-utils-test-ppc64le:
    platform: "linux/ppc64le"
    build:
      context: image
    container_name: java-native-utils-test-ppc64le
    environment:
      - QEMU=true
      - QARCH=ppc64le
    volumes:
      - ../../../:/project
    entrypoint: /usr/bin/env bash /project/JavaNativeUtilsTest/docker/ppc64le/runtest.sh


