/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_aschuetz_nativeutils_impl_JNINativeMemory */

#ifndef _Included_eu_aschuetz_nativeutils_impl_JNINativeMemory
#define _Included_eu_aschuetz_nativeutils_impl_JNINativeMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    supportsCompareAndSet16Byte
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_supportsCompareAndSet16Byte
  (JNIEnv *, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    writeExpandedByteArray
 * Signature: (JJ[BIII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_writeExpandedByteArray
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readExpandedByteArray
 * Signature: (JJ[BIII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readExpandedByteArray
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    writeExpandedCharArray
 * Signature: (JJ[CIII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_writeExpandedCharArray
  (JNIEnv *, jclass, jlong, jlong, jcharArray, jint, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readExpandedCharArray
 * Signature: (JJ[CIII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readExpandedCharArray
  (JNIEnv *, jclass, jlong, jlong, jcharArray, jint, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    writeExpandedShortArray
 * Signature: (JJ[SIII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_writeExpandedShortArray
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jint, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readExpandedShortArray
 * Signature: (JJ[SIII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readExpandedShortArray
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jint, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    writeExpandedIntArray
 * Signature: (JJ[IIII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_writeExpandedIntArray
  (JNIEnv *, jclass, jlong, jlong, jintArray, jint, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readExpandedIntArray
 * Signature: (JJ[IIII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readExpandedIntArray
  (JNIEnv *, jclass, jlong, jlong, jintArray, jint, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    writeExpandedLongArray
 * Signature: (JJ[JIII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_writeExpandedLongArray
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jint, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readExpandedLongArray
 * Signature: (JJ[JIII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readExpandedLongArray
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jint, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    writeFloatArray
 * Signature: (JJ[FII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_writeFloatArray
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readFloatArray
 * Signature: (JJ[FII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readFloatArray
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    writeDoubleArray
 * Signature: (JJ[DII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_writeDoubleArray
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readDoubleArray
 * Signature: (JJ[DII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readDoubleArray
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    supportsCompareAndSet8Byte
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_supportsCompareAndSet8Byte
  (JNIEnv *, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet8ByteAlignment
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_compareAndSet8ByteAlignment
  (JNIEnv *, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    supportsCompareAndSet4Byte
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_supportsCompareAndSet4Byte
  (JNIEnv *, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet4ByteAlignment
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_compareAndSet4ByteAlignment
  (JNIEnv *, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    supportsCompareAndSet2Byte
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_supportsCompareAndSet2Byte
  (JNIEnv *, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet2ByteAlignment
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_compareAndSet2ByteAlignment
  (JNIEnv *, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    supportsCompareAndSet1Byte
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_supportsCompareAndSet1Byte
  (JNIEnv *, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet1ByteAlignment
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_compareAndSet1ByteAlignment
  (JNIEnv *, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readUntilByte
 * Signature: (JJIB[BI)I
 */
JNIEXPORT jint JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readUntilByte
  (JNIEnv *, jclass, jlong, jlong, jint, jbyte, jbyteArray, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    indexOf
 * Signature: (JJJB)J
 */
JNIEXPORT jlong JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_indexOf
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyte);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    off
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_off
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJ[BII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_write__JJ_3BII
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJB)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_write__JJB
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_write__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_write__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_write__JJF
  (JNIEnv *, jclass, jlong, jlong, jfloat);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_write__JJD
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    write
 * Signature: (JJS)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_write__JJS
  (JNIEnv *, jclass, jlong, jlong, jshort);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    read
 * Signature: (JJ[BII)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_read
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readInt
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readInt
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readLong
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readLong
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readFloat
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readFloat
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readDouble
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readShort
 * Signature: (JJ)S
 */
JNIEXPORT jshort JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readShort
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readByte
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readByte
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    set
 * Signature: (JJBJ)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_set
  (JNIEnv *, jclass, jlong, jlong, jbyte, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    getAndAdd
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_getAndAdd__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    getAndAdd
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_getAndAdd__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    getAndAdd
 * Signature: (JJS)S
 */
JNIEXPORT jshort JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_getAndAdd__JJS
  (JNIEnv *, jclass, jlong, jlong, jshort);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    getAndAdd
 * Signature: (JJB)B
 */
JNIEXPORT jbyte JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_getAndAdd__JJB
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    getAndSet
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_getAndSet__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    getAndSet
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_getAndSet__JJI
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    getAndSet
 * Signature: (JJS)S
 */
JNIEXPORT jshort JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_getAndSet__JJS
  (JNIEnv *, jclass, jlong, jlong, jshort);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    getAndSet
 * Signature: (JJB)B
 */
JNIEXPORT jbyte JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_getAndSet__JJB
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_compareAndSet__JJJJ
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet
 * Signature: (JJII)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_compareAndSet__JJII
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet
 * Signature: (JJSS)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_compareAndSet__JJSS
  (JNIEnv *, jclass, jlong, jlong, jshort, jshort);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet
 * Signature: (JJBB)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_compareAndSet__JJBB
  (JNIEnv *, jclass, jlong, jlong, jbyte, jbyte);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    compareAndSet
 * Signature: (JJ[B)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_compareAndSet__JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJJJJJLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spinAndSet__JJJJJJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJJJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spinAndSet__JJJJJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJJJJLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spin__JJJJJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spin__JJJJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJIIJJLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spinAndSet__JJIIJJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJIIJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spinAndSet__JJIIJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJIJJLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spin__JJIJJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJIJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spin__JJIJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJSSJJLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spinAndSet__JJSSJJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jshort, jshort, jlong, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJSSJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spinAndSet__JJSSJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jshort, jshort, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJSJJLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spin__JJSJJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jshort, jlong, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJSJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spin__JJSJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jshort, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJBBJJLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spinAndSet__JJBBJJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jbyte, jbyte, jlong, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spinAndSet
 * Signature: (JJBBJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spinAndSet__JJBBJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jbyte, jbyte, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJBJJLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spin__JJBJJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jbyte, jlong, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    spin
 * Signature: (JJBJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_spin__JJBJLjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jlong, jlong, jbyte, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    memmove
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_memmove
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    readBuffer
 * Signature: (JJLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_readBuffer
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeMemory
 * Method:    writeBuffer
 * Signature: (JJLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeMemory_writeBuffer
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
