/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_aschuetz_nativeutils_impl_NativeLibraryLoaderHelper */

#ifndef _Included_eu_aschuetz_nativeutils_impl_NativeLibraryLoaderHelper
#define _Included_eu_aschuetz_nativeutils_impl_NativeLibraryLoaderHelper
#ifdef __cplusplus
extern "C" {
#endif
#undef eu_aschuetz_nativeutils_impl_NativeLibraryLoaderHelper_EXPECTED_NATIVE_LIB_VERSION
#define eu_aschuetz_nativeutils_impl_NativeLibraryLoaderHelper_EXPECTED_NATIVE_LIB_VERSION 9L
/*
 * Class:     eu_aschuetz_nativeutils_impl_NativeLibraryLoaderHelper
 * Method:    getNativeLibVersion
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_eu_aschuetz_nativeutils_impl_NativeLibraryLoaderHelper_getNativeLibVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
