/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_aschuetz_nativeutils_impl_JNINativeField */

#ifndef _Included_eu_aschuetz_nativeutils_impl_JNINativeField
#define _Included_eu_aschuetz_nativeutils_impl_JNINativeField
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetObjectField
 * Signature: (JLjava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetObjectField
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetStaticObjectField
 * Signature: (JLjava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetStaticObjectField
  (JNIEnv *, jclass, jlong, jclass);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetIntField
 * Signature: (JLjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetIntField
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetStaticIntField
 * Signature: (JLjava/lang/Class;)I
 */
JNIEXPORT jint JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetStaticIntField
  (JNIEnv *, jclass, jlong, jclass);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetLongField
 * Signature: (JLjava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetLongField
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetStaticLongField
 * Signature: (JLjava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetStaticLongField
  (JNIEnv *, jclass, jlong, jclass);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetDoubleField
 * Signature: (JLjava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetDoubleField
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetStaticDoubleField
 * Signature: (JLjava/lang/Class;)D
 */
JNIEXPORT jdouble JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetStaticDoubleField
  (JNIEnv *, jclass, jlong, jclass);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetFloatField
 * Signature: (JLjava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetFloatField
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetStaticFloatField
 * Signature: (JLjava/lang/Class;)F
 */
JNIEXPORT jfloat JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetStaticFloatField
  (JNIEnv *, jclass, jlong, jclass);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetShortField
 * Signature: (JLjava/lang/Object;)S
 */
JNIEXPORT jshort JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetShortField
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetStaticShortField
 * Signature: (JLjava/lang/Class;)S
 */
JNIEXPORT jshort JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetStaticShortField
  (JNIEnv *, jclass, jlong, jclass);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetCharField
 * Signature: (JLjava/lang/Object;)C
 */
JNIEXPORT jchar JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetCharField
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetStaticCharField
 * Signature: (JLjava/lang/Class;)C
 */
JNIEXPORT jchar JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetStaticCharField
  (JNIEnv *, jclass, jlong, jclass);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetByteField
 * Signature: (JLjava/lang/Object;)B
 */
JNIEXPORT jbyte JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetByteField
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetStaticByteField
 * Signature: (JLjava/lang/Class;)B
 */
JNIEXPORT jbyte JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetStaticByteField
  (JNIEnv *, jclass, jlong, jclass);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetBooleanField
 * Signature: (JLjava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetBooleanField
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _GetStaticBooleanField
 * Signature: (JLjava/lang/Class;)Z
 */
JNIEXPORT jboolean JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1GetStaticBooleanField
  (JNIEnv *, jclass, jlong, jclass);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetObjectField
 * Signature: (JLjava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetObjectField
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetStaticObjectField
 * Signature: (JLjava/lang/Class;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetStaticObjectField
  (JNIEnv *, jclass, jlong, jclass, jobject);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetIntField
 * Signature: (JLjava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetIntField
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetStaticIntField
 * Signature: (JLjava/lang/Class;I)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetStaticIntField
  (JNIEnv *, jclass, jlong, jclass, jint);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetLongField
 * Signature: (JLjava/lang/Object;J)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetLongField
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetStaticLongField
 * Signature: (JLjava/lang/Class;J)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetStaticLongField
  (JNIEnv *, jclass, jlong, jclass, jlong);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetDoubleField
 * Signature: (JLjava/lang/Object;D)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetDoubleField
  (JNIEnv *, jclass, jlong, jobject, jdouble);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetStaticDoubleField
 * Signature: (JLjava/lang/Class;D)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetStaticDoubleField
  (JNIEnv *, jclass, jlong, jclass, jdouble);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetFloatField
 * Signature: (JLjava/lang/Object;F)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetFloatField
  (JNIEnv *, jclass, jlong, jobject, jfloat);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetStaticFloatField
 * Signature: (JLjava/lang/Class;F)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetStaticFloatField
  (JNIEnv *, jclass, jlong, jclass, jfloat);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetShortField
 * Signature: (JLjava/lang/Object;S)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetShortField
  (JNIEnv *, jclass, jlong, jobject, jshort);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetStaticShortField
 * Signature: (JLjava/lang/Class;S)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetStaticShortField
  (JNIEnv *, jclass, jlong, jclass, jshort);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetCharField
 * Signature: (JLjava/lang/Object;C)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetCharField
  (JNIEnv *, jclass, jlong, jobject, jchar);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetStaticCharField
 * Signature: (JLjava/lang/Class;C)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetStaticCharField
  (JNIEnv *, jclass, jlong, jclass, jchar);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetByteField
 * Signature: (JLjava/lang/Object;B)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetByteField
  (JNIEnv *, jclass, jlong, jobject, jbyte);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetStaticByteField
 * Signature: (JLjava/lang/Class;B)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetStaticByteField
  (JNIEnv *, jclass, jlong, jclass, jbyte);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetBooleanField
 * Signature: (JLjava/lang/Object;Z)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetBooleanField
  (JNIEnv *, jclass, jlong, jobject, jboolean);

/*
 * Class:     eu_aschuetz_nativeutils_impl_JNINativeField
 * Method:    _SetStaticBooleanField
 * Signature: (JLjava/lang/Class;Z)V
 */
JNIEXPORT void JNICALL Java_eu_aschuetz_nativeutils_impl_JNINativeField__1SetStaticBooleanField
  (JNIEnv *, jclass, jlong, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
