//THIS FILE IS MACHINE GENERATED, DO NOT EDIT
#include <jni.h>
#include <stddef.h>

/**
 * initializes the the state of the generated code. Must be called once when your library loads. 
 * returns true if initialization succeeds. If this method returns false then an exception is pending in the JNIEnv that explains the error.
 * it is recommended to call this method in your JNI_OnLoad method
*/
jboolean jnigenerator_init(JNIEnv * env);

/**
 * destroys the the state of the generated code. You can safely call jnigenerator_init() again afterwards. 
 * it is recommended to call this method in your JNI_OnUnload method
*/
void jnigenerator_destroy(JNIEnv * env);

/**
 * equivalent to (*env)->ExceptionCheck(env) just much shorter to write.
 */
jboolean jerr(JNIEnv * env);

/**
 * Creates a new byte array of the given length and copies the give buffer into it.
 * Return NULL when array creation fails. In this case a java exception is thrown.
 */
jbyteArray jarrayB(JNIEnv * env, jbyte * buffer, jsize len);

/**
 * Returns the enum ordinal or -1 if the passed enum value is NULL.
 */
jint jenum_ordinal(JNIEnv * env, jobject enumValue);

/**
 * Returns the name of the enum constant or NULL passed enum value is NULL.
 */
jstring jenum_name(JNIEnv * env, jobject enumValue);

jboolean jinstanceof_IpAdapterAddresses(JNIEnv * env, jobject value);
jboolean jinstanceof_IllegalStateException(JNIEnv * env, jobject value);
jboolean jinstanceof_Win32FileAttributeData(JNIEnv * env, jobject value);
jboolean jinstanceof_IpAdapterAddresses$IpAdapterUnicastAddress(JNIEnv * env, jobject value);
jboolean jinstanceof_PermissionDeniedException(JNIEnv * env, jobject value);
jboolean jinstanceof_GUID(JNIEnv * env, jobject value);
jboolean jinstanceof_NullPointerException(JNIEnv * env, jobject value);
jboolean jinstanceof_Utsname(JNIEnv * env, jobject value);
jboolean jinstanceof_InetAddress(JNIEnv * env, jobject value);
jboolean jinstanceof_PollFD(JNIEnv * env, jobject value);
jboolean jinstanceof_RegEnumKeyExResult(JNIEnv * env, jobject value);
jboolean jinstanceof_RegData$RegType(JNIEnv * env, jobject value);
jboolean jinstanceof_RegData(JNIEnv * env, jobject value);
jboolean jinstanceof_Collection(JNIEnv * env, jobject value);
jboolean jinstanceof_SpDeviceInterfaceData(JNIEnv * env, jobject value);
jboolean jinstanceof_NotLinkException(JNIEnv * env, jobject value);
jboolean jinstanceof_MibIpForwardRow2(JNIEnv * env, jobject value);
jboolean jinstanceof_Msghdr(JNIEnv * env, jobject value);
jboolean jinstanceof_MibIpForwardRow(JNIEnv * env, jobject value);
jboolean jinstanceof_InetSocketAddress(JNIEnv * env, jobject value);
jboolean jinstanceof_MibIpForwardRow$MIB_IPFORWARD_TYPE(JNIEnv * env, jobject value);
jboolean jinstanceof_FileNotFoundException(JNIEnv * env, jobject value);
jboolean jinstanceof_Exception(JNIEnv * env, jobject value);
jboolean jinstanceof_InvalidFileDescriptorException(JNIEnv * env, jobject value);
jboolean jinstanceof_PollFD$PollEvent(JNIEnv * env, jobject value);
jboolean jinstanceof_Iovec(JNIEnv * env, jobject value);
jboolean jinstanceof_MibIpForwardRow$MIB_IPFORWARD_PROTO(JNIEnv * env, jobject value);
jboolean jinstanceof_Sockaddr(JNIEnv * env, jobject value);
jboolean jinstanceof_AccessDeniedException(JNIEnv * env, jobject value);
jboolean jinstanceof_ReadOnlyFileSystemException(JNIEnv * env, jobject value);
jboolean jinstanceof_FileIsDirectoryException(JNIEnv * env, jobject value);
jboolean jinstanceof_Passwd(JNIEnv * env, jobject value);
jboolean jinstanceof_OperationInProgressException(JNIEnv * env, jobject value);
jboolean jinstanceof_UnrecoverableMutexException(JNIEnv * env, jobject value);
jboolean jinstanceof_ShellExecuteException(JNIEnv * env, jobject value);
jboolean jinstanceof_SpDeviceInfoData(JNIEnv * env, jobject value);
jboolean jinstanceof_BindException(JNIEnv * env, jobject value);
jboolean jinstanceof_Iterable(JNIEnv * env, jobject value);
jboolean jinstanceof_ArrayList(JNIEnv * env, jobject value);
jboolean jinstanceof_IfNameIndex(JNIEnv * env, jobject value);
jboolean jinstanceof_IllegalMonitorStateException(JNIEnv * env, jobject value);
jboolean jinstanceof_Cmsghdr(JNIEnv * env, jobject value);
jboolean jinstanceof_InvalidPathException(JNIEnv * env, jobject value);
jboolean jinstanceof_FileSystemLoopException(JNIEnv * env, jobject value);
jboolean jinstanceof_UnknownNativeErrorException(JNIEnv * env, jobject value);
jboolean jinstanceof_ConnectException(JNIEnv * env, jobject value);
jboolean jinstanceof_NoSuchElementException(JNIEnv * env, jobject value);
jboolean jinstanceof_UnsupportedOperationException(JNIEnv * env, jobject value);
jboolean jinstanceof_Stat(JNIEnv * env, jobject value);
jboolean jinstanceof_Iterator(JNIEnv * env, jobject value);
jboolean jinstanceof_NotDirectoryException(JNIEnv * env, jobject value);
jboolean jinstanceof_IOException(JNIEnv * env, jobject value);
jboolean jinstanceof_Group(JNIEnv * env, jobject value);
jboolean jinstanceof_IllegalArgumentException(JNIEnv * env, jobject value);
jboolean jinstanceof_FileAlreadyExistsException(JNIEnv * env, jobject value);
jboolean jinstanceof_QuotaExceededException(JNIEnv * env, jobject value);
jboolean jinstanceof_Statvfs(JNIEnv * env, jobject value);
jboolean jinstanceof_RegQueryInfoKeyResult(JNIEnv * env, jobject value);
jboolean jinstanceof_MutexAbandonedException(JNIEnv * env, jobject value);
jboolean jinstanceof_OutOfMemoryError(JNIEnv * env, jobject value);
jboolean jinstanceof_InconsistentMutexException(JNIEnv * env, jobject value);
jboolean jinstanceof_SharingViolationException(JNIEnv * env, jobject value);
void jset_Cmsghdr_cmsg_level(JNIEnv * env, jobject instance, jint value);
jint jget_Cmsghdr_cmsg_level(JNIEnv * env, jobject instance);
void jset_Cmsghdr_cmsg_type(JNIEnv * env, jobject instance, jint value);
jint jget_Cmsghdr_cmsg_type(JNIEnv * env, jobject instance);
void jset_Cmsghdr_payload(JNIEnv * env, jobject instance, jbyteArray value);
jboolean jsetA_Cmsghdr_payload(JNIEnv * env, jobject instance, jbyte * value, jsize len);
jbyteArray jget_Cmsghdr_payload(JNIEnv * env, jobject instance);
jobject jnew_Cmsghdr(JNIEnv * env);
jint jcall_Cmsghdr_getLevel(JNIEnv * env, jobject instance);
jbyteArray jcall_Cmsghdr_getPayload(JNIEnv * env, jobject instance);
jint jcall_Cmsghdr_getType(JNIEnv * env, jobject instance);
void jcall_Cmsghdr_setPayload(JNIEnv * env, jobject instance, jbyteArray p0);
void jset_GUID_data1(JNIEnv * env, jobject instance, jint value);
jint jget_GUID_data1(JNIEnv * env, jobject instance);
void jset_GUID_data2(JNIEnv * env, jobject instance, jshort value);
jshort jget_GUID_data2(JNIEnv * env, jobject instance);
void jset_GUID_data3(JNIEnv * env, jobject instance, jshort value);
jshort jget_GUID_data3(JNIEnv * env, jobject instance);
void jset_GUID_data4(JNIEnv * env, jobject instance, jbyteArray value);
jboolean jsetA_GUID_data4(JNIEnv * env, jobject instance, jbyte * value, jsize len);
jbyteArray jget_GUID_data4(JNIEnv * env, jobject instance);
jobject jnew_GUID(JNIEnv * env);
jobject jnew_GUID_1(JNIEnv * env, jstring p0);
jobject jcall_GUID_clone(JNIEnv * env, jobject instance);
jint jcall_GUID_getData1(JNIEnv * env, jobject instance);
jshort jcall_GUID_getData2(JNIEnv * env, jobject instance);
jshort jcall_GUID_getData3(JNIEnv * env, jobject instance);
jbyteArray jcall_GUID_getData4(JNIEnv * env, jobject instance);
void jcall_GUID_setData1(JNIEnv * env, jobject instance, jint p0);
void jcall_GUID_setData2(JNIEnv * env, jobject instance, jshort p0);
void jcall_GUID_setData3(JNIEnv * env, jobject instance, jshort p0);
void jcall_GUID_setData4(JNIEnv * env, jobject instance, jbyteArray p0);
jstring jcall_GUID_toString(JNIEnv * env, jobject instance);
void jset_Group_gr_gid(JNIEnv * env, jobject instance, jint value);
jint jget_Group_gr_gid(JNIEnv * env, jobject instance);
void jset_Group_gr_name(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_Group_gr_name(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_Group_gr_name(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_Group_gr_name(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_Group_gr_name(JNIEnv * env, jobject instance);
void jset_Group_gr_passwd(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_Group_gr_passwd(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_Group_gr_passwd(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_Group_gr_passwd(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_Group_gr_passwd(JNIEnv * env, jobject instance);
void jset_Group_gr_mem(JNIEnv * env, jobject instance, jobject value);
jobject jget_Group_gr_mem(JNIEnv * env, jobject instance);
jobject jnew_Group(JNIEnv * env);
jboolean jcall_Group_equals(JNIEnv * env, jobject instance, jobject p0);
jint jcall_Group_getGr_gid(JNIEnv * env, jobject instance);
jobject jcall_Group_getGr_mem(JNIEnv * env, jobject instance);
jstring jcall_Group_getGr_name(JNIEnv * env, jobject instance);
jstring jcall_Group_getGr_passwd(JNIEnv * env, jobject instance);
jint jcall_Group_hashCode(JNIEnv * env, jobject instance);
void jcall_Group_setGr_gid(JNIEnv * env, jobject instance, jint p0);
void jcall_Group_setGr_mem(JNIEnv * env, jobject instance, jobject p0);
void jcall_Group_setGr_name(JNIEnv * env, jobject instance, jstring p0);
void jcall_Group_setGr_passwd(JNIEnv * env, jobject instance, jstring p0);
jstring jcall_Group_toString(JNIEnv * env, jobject instance);
void jset_IfNameIndex_index(JNIEnv * env, jobject instance, jint value);
jint jget_IfNameIndex_index(JNIEnv * env, jobject instance);
void jset_IfNameIndex_name(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_IfNameIndex_name(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_IfNameIndex_name(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_IfNameIndex_name(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_IfNameIndex_name(JNIEnv * env, jobject instance);
jobject jnew_IfNameIndex(JNIEnv * env, jint p0, jstring p1);
jboolean jcall_IfNameIndex_equals(JNIEnv * env, jobject instance, jobject p0);
jint jcall_IfNameIndex_getIndex(JNIEnv * env, jobject instance);
jstring jcall_IfNameIndex_getName(JNIEnv * env, jobject instance);
jint jcall_IfNameIndex_hashCode(JNIEnv * env, jobject instance);
void jset_Iovec_payload(JNIEnv * env, jobject instance, jbyteArray value);
jboolean jsetA_Iovec_payload(JNIEnv * env, jobject instance, jbyte * value, jsize len);
jbyteArray jget_Iovec_payload(JNIEnv * env, jobject instance);
void jset_Iovec_off(JNIEnv * env, jobject instance, jint value);
jint jget_Iovec_off(JNIEnv * env, jobject instance);
void jset_Iovec_len(JNIEnv * env, jobject instance, jint value);
jint jget_Iovec_len(JNIEnv * env, jobject instance);
void jset_Iovec_size(JNIEnv * env, jobject instance, jint value);
jint jget_Iovec_size(JNIEnv * env, jobject instance);
jobject jnew_Iovec(JNIEnv * env, jint p0);
jobject jnew_Iovec_1(JNIEnv * env, jbyteArray p0);
jobject jnew_Iovec_2(JNIEnv * env, jbyteArray p0, jint p1, jint p2);
jint jcall_Iovec_getLen(JNIEnv * env, jobject instance);
jint jcall_Iovec_getOff(JNIEnv * env, jobject instance);
jbyteArray jcall_Iovec_getPayload(JNIEnv * env, jobject instance);
jint jcall_Iovec_getSize(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_AdapterName(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_IpAdapterAddresses_AdapterName(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_IpAdapterAddresses_AdapterName(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_IpAdapterAddresses_AdapterName(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_IpAdapterAddresses_AdapterName(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_UnicastAddress(JNIEnv * env, jobject instance, jobject value);
jobject jget_IpAdapterAddresses_UnicastAddress(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_AnycastAddress(JNIEnv * env, jobject instance, jobject value);
jobject jget_IpAdapterAddresses_AnycastAddress(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_MulticastAddress(JNIEnv * env, jobject instance, jobject value);
jobject jget_IpAdapterAddresses_MulticastAddress(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_DnsServerAddress(JNIEnv * env, jobject instance, jobject value);
jobject jget_IpAdapterAddresses_DnsServerAddress(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_DnsSuffix(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_IpAdapterAddresses_DnsSuffix(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_IpAdapterAddresses_DnsSuffix(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_IpAdapterAddresses_DnsSuffix(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_IpAdapterAddresses_DnsSuffix(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Description(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_IpAdapterAddresses_Description(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_IpAdapterAddresses_Description(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_IpAdapterAddresses_Description(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_IpAdapterAddresses_Description(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_FriendlyName(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_IpAdapterAddresses_FriendlyName(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_IpAdapterAddresses_FriendlyName(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_IpAdapterAddresses_FriendlyName(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_IpAdapterAddresses_FriendlyName(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_PhysicalAddress(JNIEnv * env, jobject instance, jbyteArray value);
jboolean jsetA_IpAdapterAddresses_PhysicalAddress(JNIEnv * env, jobject instance, jbyte * value, jsize len);
jbyteArray jget_IpAdapterAddresses_PhysicalAddress(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Mtu(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses_Mtu(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_IfType(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses_IfType(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_OperStatus(JNIEnv * env, jobject instance, jint value);
jint jget_IpAdapterAddresses_OperStatus(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Ipv6IfIndex(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses_Ipv6IfIndex(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_ZoneIndices(JNIEnv * env, jobject instance, jlongArray value);
jboolean jsetA_IpAdapterAddresses_ZoneIndices(JNIEnv * env, jobject instance, jlong * value, jsize len);
jlongArray jget_IpAdapterAddresses_ZoneIndices(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Prefix(JNIEnv * env, jobject instance, jobject value);
jobject jget_IpAdapterAddresses_Prefix(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_TransmitLinkSpeed(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses_TransmitLinkSpeed(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_ReceiveLinkSpeed(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses_ReceiveLinkSpeed(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_WinsServerAddress(JNIEnv * env, jobject instance, jobject value);
jobject jget_IpAdapterAddresses_WinsServerAddress(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_GatewayAddress(JNIEnv * env, jobject instance, jobject value);
jobject jget_IpAdapterAddresses_GatewayAddress(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Ipv4Metric(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses_Ipv4Metric(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Ipv6Metric(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses_Ipv6Metric(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Luid_Value(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses_Luid_Value(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Luid_NetLuidIndex(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses_Luid_NetLuidIndex(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Luid_IfType(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses_Luid_IfType(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Dhcpv4Server(JNIEnv * env, jobject instance, jobject value);
jobject jget_IpAdapterAddresses_Dhcpv4Server(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_CompartmentId(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses_CompartmentId(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_NetworkGuid(JNIEnv * env, jobject instance, jobject value);
jobject jget_IpAdapterAddresses_NetworkGuid(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_ConnectionType(JNIEnv * env, jobject instance, jint value);
jint jget_IpAdapterAddresses_ConnectionType(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_TunnelType(JNIEnv * env, jobject instance, jint value);
jint jget_IpAdapterAddresses_TunnelType(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Dhcpv6Server(JNIEnv * env, jobject instance, jobject value);
jobject jget_IpAdapterAddresses_Dhcpv6Server(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Dhcpv6ClientDuid(JNIEnv * env, jobject instance, jbyteArray value);
jboolean jsetA_IpAdapterAddresses_Dhcpv6ClientDuid(JNIEnv * env, jobject instance, jbyte * value, jsize len);
jbyteArray jget_IpAdapterAddresses_Dhcpv6ClientDuid(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses_Dhcpv6Iaid(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses_Dhcpv6Iaid(JNIEnv * env, jobject instance);
jobject jnew_IpAdapterAddresses(JNIEnv * env);
jstring jcall_IpAdapterAddresses_getAdapterName(JNIEnv * env, jobject instance);
jobject jcall_IpAdapterAddresses_getAnycastAddress(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses_getCompartmentId(JNIEnv * env, jobject instance);
jint jcall_IpAdapterAddresses_getConnectionType(JNIEnv * env, jobject instance);
jstring jcall_IpAdapterAddresses_getDescription(JNIEnv * env, jobject instance);
jobject jcall_IpAdapterAddresses_getDhcpv4Server(JNIEnv * env, jobject instance);
jbyteArray jcall_IpAdapterAddresses_getDhcpv6ClientDuid(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses_getDhcpv6Iaid(JNIEnv * env, jobject instance);
jobject jcall_IpAdapterAddresses_getDhcpv6Server(JNIEnv * env, jobject instance);
jobject jcall_IpAdapterAddresses_getDnsServerAddress(JNIEnv * env, jobject instance);
jstring jcall_IpAdapterAddresses_getDnsSuffix(JNIEnv * env, jobject instance);
jstring jcall_IpAdapterAddresses_getFriendlyName(JNIEnv * env, jobject instance);
jobject jcall_IpAdapterAddresses_getGatewayAddress(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses_getIfType(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses_getIpv4Metric(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses_getIpv6IfIndex(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses_getIpv6Metric(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses_getLuid_IfType(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses_getLuid_NetLuidIndex(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses_getLuid_Value(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses_getMtu(JNIEnv * env, jobject instance);
jobject jcall_IpAdapterAddresses_getMulticastAddress(JNIEnv * env, jobject instance);
jobject jcall_IpAdapterAddresses_getNetworkGuid(JNIEnv * env, jobject instance);
jint jcall_IpAdapterAddresses_getOperStatus(JNIEnv * env, jobject instance);
jbyteArray jcall_IpAdapterAddresses_getPhysicalAddress(JNIEnv * env, jobject instance);
jobject jcall_IpAdapterAddresses_getPrefix(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses_getReceiveLinkSpeed(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses_getTransmitLinkSpeed(JNIEnv * env, jobject instance);
jint jcall_IpAdapterAddresses_getTunnelType(JNIEnv * env, jobject instance);
jobject jcall_IpAdapterAddresses_getUnicastAddress(JNIEnv * env, jobject instance);
jobject jcall_IpAdapterAddresses_getWinsServerAddress(JNIEnv * env, jobject instance);
jlongArray jcall_IpAdapterAddresses_getZoneIndices(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses$IpAdapterUnicastAddress_Address(JNIEnv * env, jobject instance, jobject value);
jobject jget_IpAdapterAddresses$IpAdapterUnicastAddress_Address(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses$IpAdapterUnicastAddress_PrefixOrigin(JNIEnv * env, jobject instance, jint value);
jint jget_IpAdapterAddresses$IpAdapterUnicastAddress_PrefixOrigin(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses$IpAdapterUnicastAddress_SuffixOrigin(JNIEnv * env, jobject instance, jint value);
jint jget_IpAdapterAddresses$IpAdapterUnicastAddress_SuffixOrigin(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses$IpAdapterUnicastAddress_DadState(JNIEnv * env, jobject instance, jint value);
jint jget_IpAdapterAddresses$IpAdapterUnicastAddress_DadState(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses$IpAdapterUnicastAddress_ValidLifetime(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses$IpAdapterUnicastAddress_ValidLifetime(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses$IpAdapterUnicastAddress_PreferredLifetime(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses$IpAdapterUnicastAddress_PreferredLifetime(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses$IpAdapterUnicastAddress_LeaseLifetime(JNIEnv * env, jobject instance, jlong value);
jlong jget_IpAdapterAddresses$IpAdapterUnicastAddress_LeaseLifetime(JNIEnv * env, jobject instance);
void jset_IpAdapterAddresses$IpAdapterUnicastAddress_OnLinkPrefixLength(JNIEnv * env, jobject instance, jint value);
jint jget_IpAdapterAddresses$IpAdapterUnicastAddress_OnLinkPrefixLength(JNIEnv * env, jobject instance);
jobject jnew_IpAdapterAddresses$IpAdapterUnicastAddress(JNIEnv * env);
jobject jcall_IpAdapterAddresses$IpAdapterUnicastAddress_getAddress(JNIEnv * env, jobject instance);
jint jcall_IpAdapterAddresses$IpAdapterUnicastAddress_getDadState(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses$IpAdapterUnicastAddress_getLeaseLifetime(JNIEnv * env, jobject instance);
jint jcall_IpAdapterAddresses$IpAdapterUnicastAddress_getOnLinkPrefixLength(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses$IpAdapterUnicastAddress_getPreferredLifetime(JNIEnv * env, jobject instance);
jint jcall_IpAdapterAddresses$IpAdapterUnicastAddress_getPrefixOrigin(JNIEnv * env, jobject instance);
jint jcall_IpAdapterAddresses$IpAdapterUnicastAddress_getSuffixOrigin(JNIEnv * env, jobject instance);
jlong jcall_IpAdapterAddresses$IpAdapterUnicastAddress_getValidLifetime(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_dwForwardDest(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow_dwForwardDest(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_dwForwardMask(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow_dwForwardMask(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_dwForwardPolicy(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow_dwForwardPolicy(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_dwForwardNextHop(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow_dwForwardNextHop(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_dwForwardIfIndex(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow_dwForwardIfIndex(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_ForwardType(JNIEnv * env, jobject instance, jobject value);
jobject jget_MibIpForwardRow_ForwardType(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_ForwardProto(JNIEnv * env, jobject instance, jobject value);
jobject jget_MibIpForwardRow_ForwardProto(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_dwForwardAge(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow_dwForwardAge(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_dwForwardNextHopAS(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow_dwForwardNextHopAS(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_dwForwardMetric1(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow_dwForwardMetric1(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_dwForwardMetric2(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow_dwForwardMetric2(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_dwForwardMetric3(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow_dwForwardMetric3(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_dwForwardMetric4(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow_dwForwardMetric4(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow_dwForwardMetric5(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow_dwForwardMetric5(JNIEnv * env, jobject instance);
jobject jnew_MibIpForwardRow(JNIEnv * env);
jint jcall_MibIpForwardRow_getDwForwardAge(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow_getDwForwardDest(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow_getDwForwardIfIndex(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow_getDwForwardMask(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow_getDwForwardMetric1(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow_getDwForwardMetric2(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow_getDwForwardMetric3(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow_getDwForwardMetric4(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow_getDwForwardMetric5(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow_getDwForwardNextHop(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow_getDwForwardNextHopAS(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow_getDwForwardPolicy(JNIEnv * env, jobject instance);
jobject jcall_MibIpForwardRow_getForwardProto(JNIEnv * env, jobject instance);
jobject jcall_MibIpForwardRow_getForwardType(JNIEnv * env, jobject instance);
void jcall_MibIpForwardRow_setDwForwardAge(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow_setDwForwardDest(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow_setDwForwardIfIndex(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow_setDwForwardMask(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow_setDwForwardMetric1(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow_setDwForwardMetric2(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow_setDwForwardMetric3(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow_setDwForwardMetric4(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow_setDwForwardMetric5(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow_setDwForwardNextHop(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow_setDwForwardNextHopAS(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow_setDwForwardPolicy(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow_setForwardProto(JNIEnv * env, jobject instance, jobject p0);
void jcall_MibIpForwardRow_setForwardType(JNIEnv * env, jobject instance, jobject p0);
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_OTHER();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_LOCAL();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_NETMGMT();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_ICMP();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_EGP();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_GGP();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_HELLO();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_RIP();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_IS_IS();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_ES_IS();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_CISCO();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_BBN();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_OSPF();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_BGP();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_NT_AUTOSTATIC();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_NT_STATIC();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_MIB_IPPROTO_NT_STATIC_NON_DOD();
void jset_MibIpForwardRow$MIB_IPFORWARD_PROTO_dwForwardProto(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow$MIB_IPFORWARD_PROTO_dwForwardProto(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow$MIB_IPFORWARD_PROTO_$VALUES(JNIEnv * env, jobjectArray value);
jobjectArray jget_MibIpForwardRow$MIB_IPFORWARD_PROTO_$VALUES(JNIEnv * env);
jsize jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_count();
jobject* jenum_MibIpForwardRow$MIB_IPFORWARD_PROTO_values();
jobject jnew_MibIpForwardRow$MIB_IPFORWARD_PROTO(JNIEnv * env, jstring p0, jint p1, jint p2);
jint jcall_MibIpForwardRow$MIB_IPFORWARD_PROTO_getDwForwardProto(JNIEnv * env, jobject instance);
jobject jcall_MibIpForwardRow$MIB_IPFORWARD_PROTO_getForDwForwardProto(JNIEnv * env, jint p0);
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_TYPE_MIB_IPROUTE_TYPE_OTHER();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_TYPE_MIB_IPROUTE_TYPE_INVALID();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_TYPE_MIB_IPROUTE_TYPE_DIRECT();
jobject jenum_MibIpForwardRow$MIB_IPFORWARD_TYPE_MIB_IPROUTE_TYPE_INDIRECT();
void jset_MibIpForwardRow$MIB_IPFORWARD_TYPE_dwForwardType(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow$MIB_IPFORWARD_TYPE_dwForwardType(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow$MIB_IPFORWARD_TYPE_$VALUES(JNIEnv * env, jobjectArray value);
jobjectArray jget_MibIpForwardRow$MIB_IPFORWARD_TYPE_$VALUES(JNIEnv * env);
jsize jenum_MibIpForwardRow$MIB_IPFORWARD_TYPE_count();
jobject* jenum_MibIpForwardRow$MIB_IPFORWARD_TYPE_values();
jobject jnew_MibIpForwardRow$MIB_IPFORWARD_TYPE(JNIEnv * env, jstring p0, jint p1, jint p2);
jint jcall_MibIpForwardRow$MIB_IPFORWARD_TYPE_getDwForwardType(JNIEnv * env, jobject instance);
jobject jcall_MibIpForwardRow$MIB_IPFORWARD_TYPE_getForDwForwardType(JNIEnv * env, jint p0);
void jset_MibIpForwardRow2_InterfaceLuid(JNIEnv * env, jobject instance, jlong value);
jlong jget_MibIpForwardRow2_InterfaceLuid(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_InterfaceIndex(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow2_InterfaceIndex(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_DestinationPrefixAddress(JNIEnv * env, jobject instance, jobject value);
jobject jget_MibIpForwardRow2_DestinationPrefixAddress(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_DestinationPrefixLength(JNIEnv * env, jobject instance, jint value);
jint jget_MibIpForwardRow2_DestinationPrefixLength(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_NextHop(JNIEnv * env, jobject instance, jobject value);
jobject jget_MibIpForwardRow2_NextHop(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_SitePrefixLength(JNIEnv * env, jobject instance, jbyte value);
jbyte jget_MibIpForwardRow2_SitePrefixLength(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_ValidLifetime(JNIEnv * env, jobject instance, jlong value);
jlong jget_MibIpForwardRow2_ValidLifetime(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_PreferredLifetime(JNIEnv * env, jobject instance, jlong value);
jlong jget_MibIpForwardRow2_PreferredLifetime(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_Metric(JNIEnv * env, jobject instance, jlong value);
jlong jget_MibIpForwardRow2_Metric(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_Protocol(JNIEnv * env, jobject instance, jlong value);
jlong jget_MibIpForwardRow2_Protocol(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_Loopback(JNIEnv * env, jobject instance, jboolean value);
jboolean jget_MibIpForwardRow2_Loopback(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_AutoconfigureAddress(JNIEnv * env, jobject instance, jboolean value);
jboolean jget_MibIpForwardRow2_AutoconfigureAddress(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_Publish(JNIEnv * env, jobject instance, jboolean value);
jboolean jget_MibIpForwardRow2_Publish(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_Immortal(JNIEnv * env, jobject instance, jboolean value);
jboolean jget_MibIpForwardRow2_Immortal(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_Age(JNIEnv * env, jobject instance, jlong value);
jlong jget_MibIpForwardRow2_Age(JNIEnv * env, jobject instance);
void jset_MibIpForwardRow2_Origin(JNIEnv * env, jobject instance, jlong value);
jlong jget_MibIpForwardRow2_Origin(JNIEnv * env, jobject instance);
jobject jnew_MibIpForwardRow2(JNIEnv * env);
jlong jcall_MibIpForwardRow2_getAge(JNIEnv * env, jobject instance);
jobject jcall_MibIpForwardRow2_getDestinationPrefixAddress(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow2_getDestinationPrefixLength(JNIEnv * env, jobject instance);
jint jcall_MibIpForwardRow2_getInterfaceIndex(JNIEnv * env, jobject instance);
jlong jcall_MibIpForwardRow2_getInterfaceLuid(JNIEnv * env, jobject instance);
jlong jcall_MibIpForwardRow2_getMetric(JNIEnv * env, jobject instance);
jobject jcall_MibIpForwardRow2_getNextHop(JNIEnv * env, jobject instance);
jlong jcall_MibIpForwardRow2_getOrigin(JNIEnv * env, jobject instance);
jlong jcall_MibIpForwardRow2_getPreferredLifetime(JNIEnv * env, jobject instance);
jlong jcall_MibIpForwardRow2_getProtocol(JNIEnv * env, jobject instance);
jbyte jcall_MibIpForwardRow2_getSitePrefixLength(JNIEnv * env, jobject instance);
jlong jcall_MibIpForwardRow2_getValidLifetime(JNIEnv * env, jobject instance);
jboolean jcall_MibIpForwardRow2_isAutoconfigureAddress(JNIEnv * env, jobject instance);
jboolean jcall_MibIpForwardRow2_isImmortal(JNIEnv * env, jobject instance);
jboolean jcall_MibIpForwardRow2_isLoopback(JNIEnv * env, jobject instance);
jboolean jcall_MibIpForwardRow2_isPublish(JNIEnv * env, jobject instance);
void jcall_MibIpForwardRow2_setAge(JNIEnv * env, jobject instance, jlong p0);
void jcall_MibIpForwardRow2_setAutoconfigureAddress(JNIEnv * env, jobject instance, jboolean p0);
void jcall_MibIpForwardRow2_setDestinationPrefixAddress(JNIEnv * env, jobject instance, jobject p0);
void jcall_MibIpForwardRow2_setDestinationPrefixLength(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow2_setImmortal(JNIEnv * env, jobject instance, jboolean p0);
void jcall_MibIpForwardRow2_setInterfaceIndex(JNIEnv * env, jobject instance, jint p0);
void jcall_MibIpForwardRow2_setInterfaceLuid(JNIEnv * env, jobject instance, jlong p0);
void jcall_MibIpForwardRow2_setLoopback(JNIEnv * env, jobject instance, jboolean p0);
void jcall_MibIpForwardRow2_setMetric(JNIEnv * env, jobject instance, jlong p0);
void jcall_MibIpForwardRow2_setNextHop(JNIEnv * env, jobject instance, jobject p0);
void jcall_MibIpForwardRow2_setOrigin(JNIEnv * env, jobject instance, jlong p0);
void jcall_MibIpForwardRow2_setPreferredLifetime(JNIEnv * env, jobject instance, jlong p0);
void jcall_MibIpForwardRow2_setProtocol(JNIEnv * env, jobject instance, jlong p0);
void jcall_MibIpForwardRow2_setPublish(JNIEnv * env, jobject instance, jboolean p0);
void jcall_MibIpForwardRow2_setSitePrefixLength(JNIEnv * env, jobject instance, jbyte p0);
void jcall_MibIpForwardRow2_setValidLifetime(JNIEnv * env, jobject instance, jlong p0);
jstring jcall_MibIpForwardRow2_toString(JNIEnv * env, jobject instance);
void jset_Msghdr_msg_iov(JNIEnv * env, jobject instance, jobjectArray value);
jobjectArray jget_Msghdr_msg_iov(JNIEnv * env, jobject instance);
void jset_Msghdr_msg_control(JNIEnv * env, jobject instance, jbyteArray value);
jboolean jsetA_Msghdr_msg_control(JNIEnv * env, jobject instance, jbyte * value, jsize len);
jbyteArray jget_Msghdr_msg_control(JNIEnv * env, jobject instance);
void jset_Msghdr_msg_name(JNIEnv * env, jobject instance, jobject value);
jobject jget_Msghdr_msg_name(JNIEnv * env, jobject instance);
void jset_Msghdr_complete(JNIEnv * env, jobject instance, jboolean value);
jboolean jget_Msghdr_complete(JNIEnv * env, jobject instance);
void jset_Msghdr_truncated(JNIEnv * env, jobject instance, jboolean value);
jboolean jget_Msghdr_truncated(JNIEnv * env, jobject instance);
void jset_Msghdr_controlDataTruncated(JNIEnv * env, jobject instance, jboolean value);
jboolean jget_Msghdr_controlDataTruncated(JNIEnv * env, jobject instance);
void jset_Msghdr_outOfBand(JNIEnv * env, jobject instance, jboolean value);
jboolean jget_Msghdr_outOfBand(JNIEnv * env, jobject instance);
void jset_Msghdr_errQueue(JNIEnv * env, jobject instance, jboolean value);
jboolean jget_Msghdr_errQueue(JNIEnv * env, jobject instance);
void jset_Msghdr_msg_controllen(JNIEnv * env, jobject instance, jint value);
jint jget_Msghdr_msg_controllen(JNIEnv * env, jobject instance);
jobject jnew_Msghdr(JNIEnv * env, jobject p0);
jobject jnew_Msghdr_1(JNIEnv * env, jobject p0, jobject p1, jbyteArray p2);
jobject jnew_Msghdr_2(JNIEnv * env, jbyteArray p0, jint p1, jint p2);
jobject jnew_Msghdr_3(JNIEnv * env, jobjectArray p0);
jobject jnew_Msghdr_4(JNIEnv * env, jobjectArray p0, jobject p1);
jobject jnew_Msghdr_5(JNIEnv * env, jobjectArray p0, jobject p1, jbyteArray p2);
jobject jnew_Msghdr_6(JNIEnv * env, jobjectArray p0, jbyteArray p1);
jbyteArray jcall_Msghdr_getMsg_control(JNIEnv * env, jobject instance);
jint jcall_Msghdr_getMsg_controllen(JNIEnv * env, jobject instance);
jobjectArray jcall_Msghdr_getMsg_iov(JNIEnv * env, jobject instance);
jobject jcall_Msghdr_getMsg_name(JNIEnv * env, jobject instance);
jboolean jcall_Msghdr_isComplete(JNIEnv * env, jobject instance);
jboolean jcall_Msghdr_isControlDataTruncated(JNIEnv * env, jobject instance);
jboolean jcall_Msghdr_isErrQueue(JNIEnv * env, jobject instance);
jboolean jcall_Msghdr_isOutOfBand(JNIEnv * env, jobject instance);
jboolean jcall_Msghdr_isTruncated(JNIEnv * env, jobject instance);
void jset_Passwd_pw_name(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_Passwd_pw_name(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_Passwd_pw_name(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_Passwd_pw_name(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_Passwd_pw_name(JNIEnv * env, jobject instance);
void jset_Passwd_pw_passwd(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_Passwd_pw_passwd(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_Passwd_pw_passwd(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_Passwd_pw_passwd(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_Passwd_pw_passwd(JNIEnv * env, jobject instance);
void jset_Passwd_pw_uid(JNIEnv * env, jobject instance, jint value);
jint jget_Passwd_pw_uid(JNIEnv * env, jobject instance);
void jset_Passwd_pw_gid(JNIEnv * env, jobject instance, jint value);
jint jget_Passwd_pw_gid(JNIEnv * env, jobject instance);
void jset_Passwd_pw_gecos(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_Passwd_pw_gecos(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_Passwd_pw_gecos(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_Passwd_pw_gecos(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_Passwd_pw_gecos(JNIEnv * env, jobject instance);
void jset_Passwd_pw_dir(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_Passwd_pw_dir(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_Passwd_pw_dir(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_Passwd_pw_dir(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_Passwd_pw_dir(JNIEnv * env, jobject instance);
void jset_Passwd_pw_shell(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_Passwd_pw_shell(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_Passwd_pw_shell(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_Passwd_pw_shell(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_Passwd_pw_shell(JNIEnv * env, jobject instance);
jobject jnew_Passwd(JNIEnv * env);
jboolean jcall_Passwd_equals(JNIEnv * env, jobject instance, jobject p0);
jstring jcall_Passwd_getPw_dir(JNIEnv * env, jobject instance);
jstring jcall_Passwd_getPw_gecos(JNIEnv * env, jobject instance);
jint jcall_Passwd_getPw_gid(JNIEnv * env, jobject instance);
jstring jcall_Passwd_getPw_name(JNIEnv * env, jobject instance);
jstring jcall_Passwd_getPw_passwd(JNIEnv * env, jobject instance);
jstring jcall_Passwd_getPw_shell(JNIEnv * env, jobject instance);
jint jcall_Passwd_getPw_uid(JNIEnv * env, jobject instance);
jint jcall_Passwd_hashCode(JNIEnv * env, jobject instance);
void jcall_Passwd_setPw_dir(JNIEnv * env, jobject instance, jstring p0);
void jcall_Passwd_setPw_gecos(JNIEnv * env, jobject instance, jstring p0);
void jcall_Passwd_setPw_gid(JNIEnv * env, jobject instance, jint p0);
void jcall_Passwd_setPw_name(JNIEnv * env, jobject instance, jstring p0);
void jcall_Passwd_setPw_passwd(JNIEnv * env, jobject instance, jstring p0);
void jcall_Passwd_setPw_shell(JNIEnv * env, jobject instance, jstring p0);
void jcall_Passwd_setPw_uid(JNIEnv * env, jobject instance, jint p0);
jstring jcall_Passwd_toString(JNIEnv * env, jobject instance);
void jset_PollFD_fd(JNIEnv * env, jobject instance, jint value);
jint jget_PollFD_fd(JNIEnv * env, jobject instance);
void jset_PollFD_events(JNIEnv * env, jobject instance, jobject value);
jobject jget_PollFD_events(JNIEnv * env, jobject instance);
void jset_PollFD_revents(JNIEnv * env, jobject instance, jobject value);
jobject jget_PollFD_revents(JNIEnv * env, jobject instance);
jobject jnew_PollFD(JNIEnv * env, jint p0, jobject p1);
jobject jcall_PollFD_getEvents(JNIEnv * env, jobject instance);
jint jcall_PollFD_getFd(JNIEnv * env, jobject instance);
jobject jcall_PollFD_getREvents(JNIEnv * env, jobject instance);
jboolean jcall_PollFD_test(JNIEnv * env, jobject instance, jobject p0);
jobject jenum_PollFD$PollEvent_POLLIN();
jobject jenum_PollFD$PollEvent_POLLPRI();
jobject jenum_PollFD$PollEvent_POLLOUT();
jobject jenum_PollFD$PollEvent_POLLRDNORM();
jobject jenum_PollFD$PollEvent_POLLRDBAND();
jobject jenum_PollFD$PollEvent_POLLWRNORM();
jobject jenum_PollFD$PollEvent_POLLWRBAND();
jobject jenum_PollFD$PollEvent_POLLMSG();
jobject jenum_PollFD$PollEvent_POLLREMOVE();
jobject jenum_PollFD$PollEvent_POLLRDHUP();
jobject jenum_PollFD$PollEvent_POLLERR();
jobject jenum_PollFD$PollEvent_POLLHUP();
jobject jenum_PollFD$PollEvent_POLLNVAL();
void jset_PollFD$PollEvent_$VALUES(JNIEnv * env, jobjectArray value);
jobjectArray jget_PollFD$PollEvent_$VALUES(JNIEnv * env);
jsize jenum_PollFD$PollEvent_count();
jobject* jenum_PollFD$PollEvent_values();
jobject jnew_PollFD$PollEvent(JNIEnv * env, jstring p0, jint p1);
void jset_RegData_type(JNIEnv * env, jobject instance, jobject value);
jobject jget_RegData_type(JNIEnv * env, jobject instance);
void jset_RegData_value(JNIEnv * env, jobject instance, jobject value);
jobject jget_RegData_value(JNIEnv * env, jobject instance);
jobject jnew_RegData(JNIEnv * env, jint p0);
jobject jnew_RegData_1(JNIEnv * env, jlong p0);
jobject jnew_RegData_2(JNIEnv * env, jobject p0, jobject p1);
jint jcall_RegData_asInt(JNIEnv * env, jobject instance);
jlong jcall_RegData_asLong(JNIEnv * env, jobject instance);
jbyteArray jcall_RegData_binary(JNIEnv * env, jobject instance);
jobject jcall_RegData_number(JNIEnv * env, jobject instance);
jstring jcall_RegData_string(JNIEnv * env, jobject instance);
jobjectArray jcall_RegData_strings(JNIEnv * env, jobject instance);
jstring jcall_RegData_toString(JNIEnv * env, jobject instance);
jobject jcall_RegData_type(JNIEnv * env, jobject instance);
jobject jcall_RegData_value(JNIEnv * env, jobject instance);
jobject jenum_RegData$RegType_REG_BINARY();
jobject jenum_RegData$RegType_REG_DWORD();
jobject jenum_RegData$RegType_REG_EXPAND_SZ();
jobject jenum_RegData$RegType_REG_LINK();
jobject jenum_RegData$RegType_REG_MULTI_SZ();
jobject jenum_RegData$RegType_REG_NONE();
jobject jenum_RegData$RegType_REG_QWORD();
jobject jenum_RegData$RegType_REG_SZ();
void jset_RegData$RegType_$VALUES(JNIEnv * env, jobjectArray value);
jobjectArray jget_RegData$RegType_$VALUES(JNIEnv * env);
jsize jenum_RegData$RegType_count();
jobject* jenum_RegData$RegType_values();
jobject jnew_RegData$RegType(JNIEnv * env, jstring p0, jint p1);
void jset_RegEnumKeyExResult_name(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_RegEnumKeyExResult_name(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_RegEnumKeyExResult_name(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_RegEnumKeyExResult_name(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_RegEnumKeyExResult_name(JNIEnv * env, jobject instance);
void jset_RegEnumKeyExResult_className(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_RegEnumKeyExResult_className(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_RegEnumKeyExResult_className(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_RegEnumKeyExResult_className(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_RegEnumKeyExResult_className(JNIEnv * env, jobject instance);
void jset_RegEnumKeyExResult_lastWriteTime(JNIEnv * env, jobject instance, jlong value);
jlong jget_RegEnumKeyExResult_lastWriteTime(JNIEnv * env, jobject instance);
jobject jnew_RegEnumKeyExResult(JNIEnv * env);
jboolean jcall_RegEnumKeyExResult_equals(JNIEnv * env, jobject instance, jobject p0);
jstring jcall_RegEnumKeyExResult_getClassName(JNIEnv * env, jobject instance);
jlong jcall_RegEnumKeyExResult_getLastWriteTime(JNIEnv * env, jobject instance);
jstring jcall_RegEnumKeyExResult_getName(JNIEnv * env, jobject instance);
jint jcall_RegEnumKeyExResult_hashCode(JNIEnv * env, jobject instance);
jstring jcall_RegEnumKeyExResult_toString(JNIEnv * env, jobject instance);
void jset_RegQueryInfoKeyResult_keyClass(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_RegQueryInfoKeyResult_keyClass(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_RegQueryInfoKeyResult_keyClass(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_RegQueryInfoKeyResult_keyClass(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_RegQueryInfoKeyResult_keyClass(JNIEnv * env, jobject instance);
void jset_RegQueryInfoKeyResult_subKeys(JNIEnv * env, jobject instance, jint value);
jint jget_RegQueryInfoKeyResult_subKeys(JNIEnv * env, jobject instance);
void jset_RegQueryInfoKeyResult_maxSubKeyLen(JNIEnv * env, jobject instance, jint value);
jint jget_RegQueryInfoKeyResult_maxSubKeyLen(JNIEnv * env, jobject instance);
void jset_RegQueryInfoKeyResult_maxClassLen(JNIEnv * env, jobject instance, jint value);
jint jget_RegQueryInfoKeyResult_maxClassLen(JNIEnv * env, jobject instance);
void jset_RegQueryInfoKeyResult_values(JNIEnv * env, jobject instance, jint value);
jint jget_RegQueryInfoKeyResult_values(JNIEnv * env, jobject instance);
void jset_RegQueryInfoKeyResult_maxValueNameLen(JNIEnv * env, jobject instance, jint value);
jint jget_RegQueryInfoKeyResult_maxValueNameLen(JNIEnv * env, jobject instance);
void jset_RegQueryInfoKeyResult_maxValueLen(JNIEnv * env, jobject instance, jint value);
jint jget_RegQueryInfoKeyResult_maxValueLen(JNIEnv * env, jobject instance);
void jset_RegQueryInfoKeyResult_securityDescriptorSize(JNIEnv * env, jobject instance, jint value);
jint jget_RegQueryInfoKeyResult_securityDescriptorSize(JNIEnv * env, jobject instance);
void jset_RegQueryInfoKeyResult_lastWriteTime(JNIEnv * env, jobject instance, jlong value);
jlong jget_RegQueryInfoKeyResult_lastWriteTime(JNIEnv * env, jobject instance);
jobject jnew_RegQueryInfoKeyResult(JNIEnv * env);
jboolean jcall_RegQueryInfoKeyResult_equals(JNIEnv * env, jobject instance, jobject p0);
jstring jcall_RegQueryInfoKeyResult_getKeyClass(JNIEnv * env, jobject instance);
jlong jcall_RegQueryInfoKeyResult_getLastWriteTime(JNIEnv * env, jobject instance);
jint jcall_RegQueryInfoKeyResult_getMaxClassLen(JNIEnv * env, jobject instance);
jint jcall_RegQueryInfoKeyResult_getMaxSubKeyLen(JNIEnv * env, jobject instance);
jint jcall_RegQueryInfoKeyResult_getMaxValueLen(JNIEnv * env, jobject instance);
jint jcall_RegQueryInfoKeyResult_getMaxValueNameLen(JNIEnv * env, jobject instance);
jint jcall_RegQueryInfoKeyResult_getSecurityDescriptorSize(JNIEnv * env, jobject instance);
jint jcall_RegQueryInfoKeyResult_getSubKeys(JNIEnv * env, jobject instance);
jint jcall_RegQueryInfoKeyResult_getValues(JNIEnv * env, jobject instance);
jint jcall_RegQueryInfoKeyResult_hashCode(JNIEnv * env, jobject instance);
jstring jcall_RegQueryInfoKeyResult_toString(JNIEnv * env, jobject instance);
void jset_Sockaddr_EMPTY(JNIEnv * env, jbyteArray value);
jbyteArray jget_Sockaddr_EMPTY(JNIEnv * env);
void jset_Sockaddr_addressFamily(JNIEnv * env, jobject instance, jint value);
jint jget_Sockaddr_addressFamily(JNIEnv * env, jobject instance);
void jset_Sockaddr_address(JNIEnv * env, jobject instance, jbyteArray value);
jboolean jsetA_Sockaddr_address(JNIEnv * env, jobject instance, jbyte * value, jsize len);
jbyteArray jget_Sockaddr_address(JNIEnv * env, jobject instance);
jobject jnew_Sockaddr(JNIEnv * env);
jobject jnew_Sockaddr_1(JNIEnv * env, jint p0, jbyteArray p1);
jobject jnew_Sockaddr_2(JNIEnv * env, jobject p0);
jobject jcall_Sockaddr_clone(JNIEnv * env, jobject instance);
void jcall_Sockaddr_copyTo(JNIEnv * env, jobject instance, jobject p0);
jboolean jcall_Sockaddr_equals(JNIEnv * env, jobject instance, jobject p0);
jbyteArray jcall_Sockaddr_getAddress(JNIEnv * env, jobject instance);
jint jcall_Sockaddr_getAddressFamily(JNIEnv * env, jobject instance);
jint jcall_Sockaddr_hashCode(JNIEnv * env, jobject instance);
jobject jcall_Sockaddr_parseWin32_SOCKADDR_INET(JNIEnv * env, jobject instance);
jstring jcall_Sockaddr_toString(JNIEnv * env, jobject instance);
void jset_SpDeviceInfoData_cbSize(JNIEnv * env, jobject instance, jint value);
jint jget_SpDeviceInfoData_cbSize(JNIEnv * env, jobject instance);
void jset_SpDeviceInfoData_InterfaceClassGuid(JNIEnv * env, jobject instance, jobject value);
jobject jget_SpDeviceInfoData_InterfaceClassGuid(JNIEnv * env, jobject instance);
void jset_SpDeviceInfoData_DevInst(JNIEnv * env, jobject instance, jint value);
jint jget_SpDeviceInfoData_DevInst(JNIEnv * env, jobject instance);
void jset_SpDeviceInfoData_ptr(JNIEnv * env, jobject instance, jlong value);
jlong jget_SpDeviceInfoData_ptr(JNIEnv * env, jobject instance);
jobject jnew_SpDeviceInfoData(JNIEnv * env);
jobject jnew_SpDeviceInfoData_1(JNIEnv * env, jint p0, jobject p1, jint p2, jlong p3);
jint jcall_SpDeviceInfoData_getCbSize(JNIEnv * env, jobject instance);
jint jcall_SpDeviceInfoData_getDevInst(JNIEnv * env, jobject instance);
jobject jcall_SpDeviceInfoData_getInterfaceClassGuid(JNIEnv * env, jobject instance);
jlong jcall_SpDeviceInfoData_getPtr(JNIEnv * env, jobject instance);
jstring jcall_SpDeviceInfoData_toString(JNIEnv * env, jobject instance);
void jset_SpDeviceInterfaceData_cbSize(JNIEnv * env, jobject instance, jint value);
jint jget_SpDeviceInterfaceData_cbSize(JNIEnv * env, jobject instance);
void jset_SpDeviceInterfaceData_InterfaceClassGuid(JNIEnv * env, jobject instance, jobject value);
jobject jget_SpDeviceInterfaceData_InterfaceClassGuid(JNIEnv * env, jobject instance);
void jset_SpDeviceInterfaceData_flags(JNIEnv * env, jobject instance, jint value);
jint jget_SpDeviceInterfaceData_flags(JNIEnv * env, jobject instance);
void jset_SpDeviceInterfaceData_ptr(JNIEnv * env, jobject instance, jlong value);
jlong jget_SpDeviceInterfaceData_ptr(JNIEnv * env, jobject instance);
jobject jnew_SpDeviceInterfaceData(JNIEnv * env);
jobject jnew_SpDeviceInterfaceData_1(JNIEnv * env, jint p0, jobject p1, jint p2);
jint jcall_SpDeviceInterfaceData_getCbSize(JNIEnv * env, jobject instance);
jint jcall_SpDeviceInterfaceData_getFlags(JNIEnv * env, jobject instance);
jobject jcall_SpDeviceInterfaceData_getInterfaceClassGuid(JNIEnv * env, jobject instance);
jlong jcall_SpDeviceInterfaceData_getPtr(JNIEnv * env, jobject instance);
jstring jcall_SpDeviceInterfaceData_toString(JNIEnv * env, jobject instance);
void jset_Stat_dev(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_dev(JNIEnv * env, jobject instance);
void jset_Stat_ino(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_ino(JNIEnv * env, jobject instance);
void jset_Stat_mode(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_mode(JNIEnv * env, jobject instance);
void jset_Stat_nlink(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_nlink(JNIEnv * env, jobject instance);
void jset_Stat_uid(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_uid(JNIEnv * env, jobject instance);
void jset_Stat_gid(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_gid(JNIEnv * env, jobject instance);
void jset_Stat_rdev(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_rdev(JNIEnv * env, jobject instance);
void jset_Stat_size(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_size(JNIEnv * env, jobject instance);
void jset_Stat_blksize(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_blksize(JNIEnv * env, jobject instance);
void jset_Stat_blocks(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_blocks(JNIEnv * env, jobject instance);
void jset_Stat_atime(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_atime(JNIEnv * env, jobject instance);
void jset_Stat_mtime(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_mtime(JNIEnv * env, jobject instance);
void jset_Stat_ctime(JNIEnv * env, jobject instance, jlong value);
jlong jget_Stat_ctime(JNIEnv * env, jobject instance);
void jset_Stat_OR(JNIEnv * env, jint value);
jint jget_Stat_OR(JNIEnv * env);
void jset_Stat_OW(JNIEnv * env, jint value);
jint jget_Stat_OW(JNIEnv * env);
void jset_Stat_OE(JNIEnv * env, jint value);
jint jget_Stat_OE(JNIEnv * env);
void jset_Stat_GR(JNIEnv * env, jint value);
jint jget_Stat_GR(JNIEnv * env);
void jset_Stat_GW(JNIEnv * env, jint value);
jint jget_Stat_GW(JNIEnv * env);
void jset_Stat_GE(JNIEnv * env, jint value);
jint jget_Stat_GE(JNIEnv * env);
void jset_Stat_ER(JNIEnv * env, jint value);
jint jget_Stat_ER(JNIEnv * env);
void jset_Stat_EW(JNIEnv * env, jint value);
jint jget_Stat_EW(JNIEnv * env);
void jset_Stat_EE(JNIEnv * env, jint value);
jint jget_Stat_EE(JNIEnv * env);
jobject jnew_Stat(JNIEnv * env);
jboolean jcall_Stat_canGroupExecute(JNIEnv * env, jobject instance);
jboolean jcall_Stat_canGroupRead(JNIEnv * env, jobject instance);
jboolean jcall_Stat_canGroupWrite(JNIEnv * env, jobject instance);
jboolean jcall_Stat_canOthersExecute(JNIEnv * env, jobject instance);
jboolean jcall_Stat_canOthersRead(JNIEnv * env, jobject instance);
jboolean jcall_Stat_canOthersWrite(JNIEnv * env, jobject instance);
jboolean jcall_Stat_canOwnerExecute(JNIEnv * env, jobject instance);
jboolean jcall_Stat_canOwnerRead(JNIEnv * env, jobject instance);
jboolean jcall_Stat_canOwnerWrite(JNIEnv * env, jobject instance);
jlong jcall_Stat_getAtime(JNIEnv * env, jobject instance);
jlong jcall_Stat_getBlksize(JNIEnv * env, jobject instance);
jlong jcall_Stat_getBlocks(JNIEnv * env, jobject instance);
jlong jcall_Stat_getCtime(JNIEnv * env, jobject instance);
jlong jcall_Stat_getDev(JNIEnv * env, jobject instance);
jlong jcall_Stat_getGid(JNIEnv * env, jobject instance);
jlong jcall_Stat_getIno(JNIEnv * env, jobject instance);
jlong jcall_Stat_getMode(JNIEnv * env, jobject instance);
jlong jcall_Stat_getMtime(JNIEnv * env, jobject instance);
jlong jcall_Stat_getNlink(JNIEnv * env, jobject instance);
jstring jcall_Stat_getPermissions(JNIEnv * env, jobject instance);
jlong jcall_Stat_getRdev(JNIEnv * env, jobject instance);
jlong jcall_Stat_getSize(JNIEnv * env, jobject instance);
jlong jcall_Stat_getUid(JNIEnv * env, jobject instance);
jboolean jcall_Stat_isBlockDevice(JNIEnv * env, jobject instance);
jboolean jcall_Stat_isCharacterDevice(JNIEnv * env, jobject instance);
jboolean jcall_Stat_isDir(JNIEnv * env, jobject instance);
jboolean jcall_Stat_isFIFO(JNIEnv * env, jobject instance);
jboolean jcall_Stat_isRegularFile(JNIEnv * env, jobject instance);
jboolean jcall_Stat_isSocket(JNIEnv * env, jobject instance);
jboolean jcall_Stat_isSymbolicLink(JNIEnv * env, jobject instance);
jstring jcall_Stat_toString(JNIEnv * env, jobject instance);
void jset_Statvfs_f_bsize(JNIEnv * env, jobject instance, jlong value);
jlong jget_Statvfs_f_bsize(JNIEnv * env, jobject instance);
void jset_Statvfs_f_frsize(JNIEnv * env, jobject instance, jlong value);
jlong jget_Statvfs_f_frsize(JNIEnv * env, jobject instance);
void jset_Statvfs_f_blocks(JNIEnv * env, jobject instance, jlong value);
jlong jget_Statvfs_f_blocks(JNIEnv * env, jobject instance);
void jset_Statvfs_f_bfree(JNIEnv * env, jobject instance, jlong value);
jlong jget_Statvfs_f_bfree(JNIEnv * env, jobject instance);
void jset_Statvfs_f_bavail(JNIEnv * env, jobject instance, jlong value);
jlong jget_Statvfs_f_bavail(JNIEnv * env, jobject instance);
void jset_Statvfs_f_files(JNIEnv * env, jobject instance, jlong value);
jlong jget_Statvfs_f_files(JNIEnv * env, jobject instance);
void jset_Statvfs_f_ffree(JNIEnv * env, jobject instance, jlong value);
jlong jget_Statvfs_f_ffree(JNIEnv * env, jobject instance);
void jset_Statvfs_f_favail(JNIEnv * env, jobject instance, jlong value);
jlong jget_Statvfs_f_favail(JNIEnv * env, jobject instance);
void jset_Statvfs_f_fsid(JNIEnv * env, jobject instance, jlong value);
jlong jget_Statvfs_f_fsid(JNIEnv * env, jobject instance);
void jset_Statvfs_f_flag(JNIEnv * env, jobject instance, jlong value);
jlong jget_Statvfs_f_flag(JNIEnv * env, jobject instance);
void jset_Statvfs_f_namemax(JNIEnv * env, jobject instance, jlong value);
jlong jget_Statvfs_f_namemax(JNIEnv * env, jobject instance);
jobject jnew_Statvfs(JNIEnv * env);
jlong jcall_Statvfs_getF_bavail(JNIEnv * env, jobject instance);
jlong jcall_Statvfs_getF_bfree(JNIEnv * env, jobject instance);
jlong jcall_Statvfs_getF_blocks(JNIEnv * env, jobject instance);
jlong jcall_Statvfs_getF_bsize(JNIEnv * env, jobject instance);
jlong jcall_Statvfs_getF_favail(JNIEnv * env, jobject instance);
jlong jcall_Statvfs_getF_ffree(JNIEnv * env, jobject instance);
jlong jcall_Statvfs_getF_files(JNIEnv * env, jobject instance);
jlong jcall_Statvfs_getF_flag(JNIEnv * env, jobject instance);
jlong jcall_Statvfs_getF_frsize(JNIEnv * env, jobject instance);
jlong jcall_Statvfs_getF_fsid(JNIEnv * env, jobject instance);
jlong jcall_Statvfs_getF_namemax(JNIEnv * env, jobject instance);
void jcall_Statvfs_setF_bavail(JNIEnv * env, jobject instance, jlong p0);
void jcall_Statvfs_setF_bfree(JNIEnv * env, jobject instance, jlong p0);
void jcall_Statvfs_setF_blocks(JNIEnv * env, jobject instance, jlong p0);
void jcall_Statvfs_setF_bsize(JNIEnv * env, jobject instance, jlong p0);
void jcall_Statvfs_setF_favail(JNIEnv * env, jobject instance, jlong p0);
void jcall_Statvfs_setF_ffree(JNIEnv * env, jobject instance, jlong p0);
void jcall_Statvfs_setF_files(JNIEnv * env, jobject instance, jlong p0);
void jcall_Statvfs_setF_flag(JNIEnv * env, jobject instance, jlong p0);
void jcall_Statvfs_setF_frsize(JNIEnv * env, jobject instance, jlong p0);
void jcall_Statvfs_setF_fsid(JNIEnv * env, jobject instance, jlong p0);
void jcall_Statvfs_setF_namemax(JNIEnv * env, jobject instance, jlong p0);
jstring jcall_Statvfs_toString(JNIEnv * env, jobject instance);
void jset_Utsname_sysname(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_Utsname_sysname(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_Utsname_sysname(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_Utsname_sysname(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_Utsname_sysname(JNIEnv * env, jobject instance);
void jset_Utsname_nodename(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_Utsname_nodename(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_Utsname_nodename(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_Utsname_nodename(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_Utsname_nodename(JNIEnv * env, jobject instance);
void jset_Utsname_release(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_Utsname_release(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_Utsname_release(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_Utsname_release(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_Utsname_release(JNIEnv * env, jobject instance);
void jset_Utsname_version(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_Utsname_version(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_Utsname_version(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_Utsname_version(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_Utsname_version(JNIEnv * env, jobject instance);
void jset_Utsname_machine(JNIEnv * env, jobject instance, jstring value);
jboolean jsetC_Utsname_machine(JNIEnv * env, jobject instance, char * value);
jboolean jsetCC_Utsname_machine(JNIEnv * env, jobject instance, const char * value);
jboolean jsetWC_Utsname_machine(JNIEnv * env, jobject instance, wchar_t * value);
jstring jget_Utsname_machine(JNIEnv * env, jobject instance);
jobject jnew_Utsname(JNIEnv * env);
jboolean jcall_Utsname_equals(JNIEnv * env, jobject instance, jobject p0);
jstring jcall_Utsname_getMachine(JNIEnv * env, jobject instance);
jstring jcall_Utsname_getNodename(JNIEnv * env, jobject instance);
jstring jcall_Utsname_getRelease(JNIEnv * env, jobject instance);
jstring jcall_Utsname_getSysname(JNIEnv * env, jobject instance);
jstring jcall_Utsname_getVersion(JNIEnv * env, jobject instance);
jint jcall_Utsname_hashCode(JNIEnv * env, jobject instance);
jstring jcall_Utsname_toString(JNIEnv * env, jobject instance);
void jset_Win32FileAttributeData_dwFileAttributes(JNIEnv * env, jobject instance, jlong value);
jlong jget_Win32FileAttributeData_dwFileAttributes(JNIEnv * env, jobject instance);
void jset_Win32FileAttributeData_nFileSizeLow(JNIEnv * env, jobject instance, jlong value);
jlong jget_Win32FileAttributeData_nFileSizeLow(JNIEnv * env, jobject instance);
void jset_Win32FileAttributeData_nFileSizeHigh(JNIEnv * env, jobject instance, jlong value);
jlong jget_Win32FileAttributeData_nFileSizeHigh(JNIEnv * env, jobject instance);
void jset_Win32FileAttributeData_ftLastAccessTimeLow(JNIEnv * env, jobject instance, jlong value);
jlong jget_Win32FileAttributeData_ftLastAccessTimeLow(JNIEnv * env, jobject instance);
void jset_Win32FileAttributeData_ftLastAccessTimeHigh(JNIEnv * env, jobject instance, jlong value);
jlong jget_Win32FileAttributeData_ftLastAccessTimeHigh(JNIEnv * env, jobject instance);
void jset_Win32FileAttributeData_ftLastWriteTimeHigh(JNIEnv * env, jobject instance, jlong value);
jlong jget_Win32FileAttributeData_ftLastWriteTimeHigh(JNIEnv * env, jobject instance);
void jset_Win32FileAttributeData_ftLastWriteTimeLow(JNIEnv * env, jobject instance, jlong value);
jlong jget_Win32FileAttributeData_ftLastWriteTimeLow(JNIEnv * env, jobject instance);
void jset_Win32FileAttributeData_ftCreationTimeHigh(JNIEnv * env, jobject instance, jlong value);
jlong jget_Win32FileAttributeData_ftCreationTimeHigh(JNIEnv * env, jobject instance);
void jset_Win32FileAttributeData_ftCreationTimeLow(JNIEnv * env, jobject instance, jlong value);
jlong jget_Win32FileAttributeData_ftCreationTimeLow(JNIEnv * env, jobject instance);
jobject jnew_Win32FileAttributeData(JNIEnv * env);
jlong jcall_Win32FileAttributeData_getDwFileAttributes(JNIEnv * env, jobject instance);
jlong jcall_Win32FileAttributeData_getFtCreationTimeHigh(JNIEnv * env, jobject instance);
jlong jcall_Win32FileAttributeData_getFtCreationTimeLow(JNIEnv * env, jobject instance);
jlong jcall_Win32FileAttributeData_getFtLastAccessTimeHigh(JNIEnv * env, jobject instance);
jlong jcall_Win32FileAttributeData_getFtLastAccessTimeLow(JNIEnv * env, jobject instance);
jlong jcall_Win32FileAttributeData_getFtLastWriteTimeHigh(JNIEnv * env, jobject instance);
jlong jcall_Win32FileAttributeData_getFtLastWriteTimeLow(JNIEnv * env, jobject instance);
jlong jcall_Win32FileAttributeData_getnFileSizeHigh(JNIEnv * env, jobject instance);
jlong jcall_Win32FileAttributeData_getnFileSizeLow(JNIEnv * env, jobject instance);
jobject jcall_Iterable_iterator(JNIEnv * env, jobject instance);
jboolean jcall_InetAddress_equals(JNIEnv * env, jobject instance, jobject p0);
jbyteArray jcall_InetAddress_getAddress(JNIEnv * env, jobject instance);
jobjectArray jcall_InetAddress_getAllByName(JNIEnv * env, jstring p0);
jobject jcall_InetAddress_getByAddress(JNIEnv * env, jstring p0, jbyteArray p1);
jobject jcall_InetAddress_getByAddress_1(JNIEnv * env, jbyteArray p0);
jobject jcall_InetAddress_getByName(JNIEnv * env, jstring p0);
jstring jcall_InetAddress_getCanonicalHostName(JNIEnv * env, jobject instance);
jstring jcall_InetAddress_getHostAddress(JNIEnv * env, jobject instance);
jstring jcall_InetAddress_getHostName(JNIEnv * env, jobject instance);
jobject jcall_InetAddress_getLocalHost(JNIEnv * env);
jobject jcall_InetAddress_getLoopbackAddress(JNIEnv * env);
jint jcall_InetAddress_hashCode(JNIEnv * env, jobject instance);
jboolean jcall_InetAddress_isAnyLocalAddress(JNIEnv * env, jobject instance);
jboolean jcall_InetAddress_isLinkLocalAddress(JNIEnv * env, jobject instance);
jboolean jcall_InetAddress_isLoopbackAddress(JNIEnv * env, jobject instance);
jboolean jcall_InetAddress_isMCGlobal(JNIEnv * env, jobject instance);
jboolean jcall_InetAddress_isMCLinkLocal(JNIEnv * env, jobject instance);
jboolean jcall_InetAddress_isMCNodeLocal(JNIEnv * env, jobject instance);
jboolean jcall_InetAddress_isMCOrgLocal(JNIEnv * env, jobject instance);
jboolean jcall_InetAddress_isMCSiteLocal(JNIEnv * env, jobject instance);
jboolean jcall_InetAddress_isMulticastAddress(JNIEnv * env, jobject instance);
jboolean jcall_InetAddress_isReachable(JNIEnv * env, jobject instance, jint p0);
jboolean jcall_InetAddress_isReachable_1(JNIEnv * env, jobject instance, jobject p0, jint p1, jint p2);
jboolean jcall_InetAddress_isSiteLocalAddress(JNIEnv * env, jobject instance);
jstring jcall_InetAddress_toString(JNIEnv * env, jobject instance);
jobject jnew_InetSocketAddress(JNIEnv * env, jint p0);
jobject jnew_InetSocketAddress_1(JNIEnv * env, jstring p0, jint p1);
jobject jnew_InetSocketAddress_2(JNIEnv * env, jobject p0, jint p1);
jobject jcall_InetSocketAddress_createUnresolved(JNIEnv * env, jstring p0, jint p1);
jboolean jcall_InetSocketAddress_equals(JNIEnv * env, jobject instance, jobject p0);
jobject jcall_InetSocketAddress_getAddress(JNIEnv * env, jobject instance);
jstring jcall_InetSocketAddress_getHostName(JNIEnv * env, jobject instance);
jstring jcall_InetSocketAddress_getHostString(JNIEnv * env, jobject instance);
jint jcall_InetSocketAddress_getPort(JNIEnv * env, jobject instance);
jint jcall_InetSocketAddress_hashCode(JNIEnv * env, jobject instance);
jboolean jcall_InetSocketAddress_isUnresolved(JNIEnv * env, jobject instance);
jstring jcall_InetSocketAddress_toString(JNIEnv * env, jobject instance);
jobject jnew_ArrayList(JNIEnv * env);
jobject jnew_ArrayList_1(JNIEnv * env, jint p0);
jobject jnew_ArrayList_2(JNIEnv * env, jobject p0);
void jcall_ArrayList_add(JNIEnv * env, jobject instance, jint p0, jobject p1);
jboolean jcall_ArrayList_add_1(JNIEnv * env, jobject instance, jobject p0);
jboolean jcall_ArrayList_addAll(JNIEnv * env, jobject instance, jint p0, jobject p1);
jboolean jcall_ArrayList_addAll_1(JNIEnv * env, jobject instance, jobject p0);
void jcall_ArrayList_clear(JNIEnv * env, jobject instance);
jobject jcall_ArrayList_clone(JNIEnv * env, jobject instance);
jboolean jcall_ArrayList_contains(JNIEnv * env, jobject instance, jobject p0);
void jcall_ArrayList_ensureCapacity(JNIEnv * env, jobject instance, jint p0);
jobject jcall_ArrayList_get(JNIEnv * env, jobject instance, jint p0);
jint jcall_ArrayList_indexOf(JNIEnv * env, jobject instance, jobject p0);
jboolean jcall_ArrayList_isEmpty(JNIEnv * env, jobject instance);
jobject jcall_ArrayList_iterator(JNIEnv * env, jobject instance);
jint jcall_ArrayList_lastIndexOf(JNIEnv * env, jobject instance, jobject p0);
jobject jcall_ArrayList_listIterator(JNIEnv * env, jobject instance);
jobject jcall_ArrayList_listIterator_1(JNIEnv * env, jobject instance, jint p0);
jobject jcall_ArrayList_remove(JNIEnv * env, jobject instance, jint p0);
jboolean jcall_ArrayList_remove_1(JNIEnv * env, jobject instance, jobject p0);
jboolean jcall_ArrayList_removeAll(JNIEnv * env, jobject instance, jobject p0);
jboolean jcall_ArrayList_retainAll(JNIEnv * env, jobject instance, jobject p0);
jobject jcall_ArrayList_set(JNIEnv * env, jobject instance, jint p0, jobject p1);
jint jcall_ArrayList_size(JNIEnv * env, jobject instance);
jobject jcall_ArrayList_subList(JNIEnv * env, jobject instance, jint p0, jint p1);
jobjectArray jcall_ArrayList_toArray(JNIEnv * env, jobject instance);
jobjectArray jcall_ArrayList_toArray_1(JNIEnv * env, jobject instance, jobjectArray p0);
void jcall_ArrayList_trimToSize(JNIEnv * env, jobject instance);
jboolean jcall_Collection_add(JNIEnv * env, jobject instance, jobject p0);
jboolean jcall_Collection_addAll(JNIEnv * env, jobject instance, jobject p0);
void jcall_Collection_clear(JNIEnv * env, jobject instance);
jboolean jcall_Collection_contains(JNIEnv * env, jobject instance, jobject p0);
jboolean jcall_Collection_containsAll(JNIEnv * env, jobject instance, jobject p0);
jboolean jcall_Collection_equals(JNIEnv * env, jobject instance, jobject p0);
jint jcall_Collection_hashCode(JNIEnv * env, jobject instance);
jboolean jcall_Collection_isEmpty(JNIEnv * env, jobject instance);
jobject jcall_Collection_iterator(JNIEnv * env, jobject instance);
jboolean jcall_Collection_remove(JNIEnv * env, jobject instance, jobject p0);
jboolean jcall_Collection_removeAll(JNIEnv * env, jobject instance, jobject p0);
jboolean jcall_Collection_retainAll(JNIEnv * env, jobject instance, jobject p0);
jint jcall_Collection_size(JNIEnv * env, jobject instance);
jobjectArray jcall_Collection_toArray(JNIEnv * env, jobject instance);
jobjectArray jcall_Collection_toArray_1(JNIEnv * env, jobject instance, jobjectArray p0);
jboolean jcall_Iterator_hasNext(JNIEnv * env, jobject instance);
jobject jcall_Iterator_next(JNIEnv * env, jobject instance);
void jcall_Iterator_remove(JNIEnv * env, jobject instance);
void jthrow_FileIsDirectoryException(JNIEnv * env, jstring p0);
void jthrowC_FileIsDirectoryException(JNIEnv * env, char* p0);
void jthrowCC_FileIsDirectoryException(JNIEnv * env, const char* p0);
void jthrow_InconsistentMutexException(JNIEnv * env);
void jthrow_InvalidFileDescriptorException(JNIEnv * env);
void jthrow_MutexAbandonedException(JNIEnv * env, jlong p0);
void jthrow_OperationInProgressException(JNIEnv * env);
void jthrow_OperationInProgressException_1(JNIEnv * env, jstring p0);
void jthrowC_OperationInProgressException_1(JNIEnv * env, char* p0);
void jthrowCC_OperationInProgressException_1(JNIEnv * env, const char* p0);
void jthrow_PermissionDeniedException(JNIEnv * env, jstring p0);
void jthrowC_PermissionDeniedException(JNIEnv * env, char* p0);
void jthrowCC_PermissionDeniedException(JNIEnv * env, const char* p0);
void jthrow_PermissionDeniedException_1(JNIEnv * env, jstring p0, jstring p1);
void jthrowC_PermissionDeniedException_1(JNIEnv * env, char* p0, char* p1);
void jthrowCC_PermissionDeniedException_1(JNIEnv * env, const char* p0, const char* p1);
void jthrow_QuotaExceededException(JNIEnv * env, jstring p0);
void jthrowC_QuotaExceededException(JNIEnv * env, char* p0);
void jthrowCC_QuotaExceededException(JNIEnv * env, const char* p0);
void jthrow_QuotaExceededException_1(JNIEnv * env, jstring p0, jstring p1, jstring p2);
void jthrowC_QuotaExceededException_1(JNIEnv * env, char* p0, char* p1, char* p2);
void jthrowCC_QuotaExceededException_1(JNIEnv * env, const char* p0, const char* p1, const char* p2);
void jthrow_SharingViolationException(JNIEnv * env, jstring p0);
void jthrowC_SharingViolationException(JNIEnv * env, char* p0);
void jthrowCC_SharingViolationException(JNIEnv * env, const char* p0);
void jthrow_SharingViolationException_1(JNIEnv * env, jstring p0, jstring p1, jstring p2);
void jthrowC_SharingViolationException_1(JNIEnv * env, char* p0, char* p1, char* p2);
void jthrowCC_SharingViolationException_1(JNIEnv * env, const char* p0, const char* p1, const char* p2);
void jthrow_ShellExecuteException(JNIEnv * env, jlong p0, jlong p1);
void jthrow_UnknownNativeErrorException(JNIEnv * env);
void jthrow_UnknownNativeErrorException_1(JNIEnv * env, jlong p0);
void jthrow_UnrecoverableMutexException(JNIEnv * env);
void jthrow_FileNotFoundException(JNIEnv * env);
void jthrow_FileNotFoundException_1(JNIEnv * env, jstring p0);
void jthrowC_FileNotFoundException_1(JNIEnv * env, char* p0);
void jthrowCC_FileNotFoundException_1(JNIEnv * env, const char* p0);
void jthrow_IOException(JNIEnv * env);
void jthrow_IOException_1(JNIEnv * env, jstring p0);
void jthrowC_IOException_1(JNIEnv * env, char* p0);
void jthrowCC_IOException_1(JNIEnv * env, const char* p0);
void jthrow_IOException_2(JNIEnv * env, jstring p0, jobject p1);
void jthrowC_IOException_2(JNIEnv * env, char* p0, jobject p1);
void jthrowCC_IOException_2(JNIEnv * env, const char* p0, jobject p1);
void jthrow_IOException_3(JNIEnv * env, jobject p0);
void jthrow_Exception(JNIEnv * env);
void jthrow_Exception_1(JNIEnv * env, jstring p0);
void jthrowC_Exception_1(JNIEnv * env, char* p0);
void jthrowCC_Exception_1(JNIEnv * env, const char* p0);
void jthrow_Exception_2(JNIEnv * env, jstring p0, jobject p1);
void jthrowC_Exception_2(JNIEnv * env, char* p0, jobject p1);
void jthrowCC_Exception_2(JNIEnv * env, const char* p0, jobject p1);
void jthrow_Exception_3(JNIEnv * env, jobject p0);
void jthrow_IllegalArgumentException(JNIEnv * env);
void jthrow_IllegalArgumentException_1(JNIEnv * env, jstring p0);
void jthrowC_IllegalArgumentException_1(JNIEnv * env, char* p0);
void jthrowCC_IllegalArgumentException_1(JNIEnv * env, const char* p0);
void jthrow_IllegalArgumentException_2(JNIEnv * env, jstring p0, jobject p1);
void jthrowC_IllegalArgumentException_2(JNIEnv * env, char* p0, jobject p1);
void jthrowCC_IllegalArgumentException_2(JNIEnv * env, const char* p0, jobject p1);
void jthrow_IllegalArgumentException_3(JNIEnv * env, jobject p0);
void jthrow_IllegalMonitorStateException(JNIEnv * env);
void jthrow_IllegalMonitorStateException_1(JNIEnv * env, jstring p0);
void jthrowC_IllegalMonitorStateException_1(JNIEnv * env, char* p0);
void jthrowCC_IllegalMonitorStateException_1(JNIEnv * env, const char* p0);
void jthrow_IllegalStateException(JNIEnv * env);
void jthrow_IllegalStateException_1(JNIEnv * env, jstring p0);
void jthrowC_IllegalStateException_1(JNIEnv * env, char* p0);
void jthrowCC_IllegalStateException_1(JNIEnv * env, const char* p0);
void jthrow_IllegalStateException_2(JNIEnv * env, jstring p0, jobject p1);
void jthrowC_IllegalStateException_2(JNIEnv * env, char* p0, jobject p1);
void jthrowCC_IllegalStateException_2(JNIEnv * env, const char* p0, jobject p1);
void jthrow_IllegalStateException_3(JNIEnv * env, jobject p0);
void jthrow_NullPointerException(JNIEnv * env);
void jthrow_NullPointerException_1(JNIEnv * env, jstring p0);
void jthrowC_NullPointerException_1(JNIEnv * env, char* p0);
void jthrowCC_NullPointerException_1(JNIEnv * env, const char* p0);
void jthrow_OutOfMemoryError(JNIEnv * env);
void jthrow_OutOfMemoryError_1(JNIEnv * env, jstring p0);
void jthrowC_OutOfMemoryError_1(JNIEnv * env, char* p0);
void jthrowCC_OutOfMemoryError_1(JNIEnv * env, const char* p0);
void jthrow_UnsupportedOperationException(JNIEnv * env);
void jthrow_UnsupportedOperationException_1(JNIEnv * env, jstring p0);
void jthrowC_UnsupportedOperationException_1(JNIEnv * env, char* p0);
void jthrowCC_UnsupportedOperationException_1(JNIEnv * env, const char* p0);
void jthrow_UnsupportedOperationException_2(JNIEnv * env, jstring p0, jobject p1);
void jthrowC_UnsupportedOperationException_2(JNIEnv * env, char* p0, jobject p1);
void jthrowCC_UnsupportedOperationException_2(JNIEnv * env, const char* p0, jobject p1);
void jthrow_UnsupportedOperationException_3(JNIEnv * env, jobject p0);
void jthrow_BindException(JNIEnv * env);
void jthrow_BindException_1(JNIEnv * env, jstring p0);
void jthrowC_BindException_1(JNIEnv * env, char* p0);
void jthrowCC_BindException_1(JNIEnv * env, const char* p0);
void jthrow_ConnectException(JNIEnv * env);
void jthrow_ConnectException_1(JNIEnv * env, jstring p0);
void jthrowC_ConnectException_1(JNIEnv * env, char* p0);
void jthrowCC_ConnectException_1(JNIEnv * env, const char* p0);
void jthrow_AccessDeniedException(JNIEnv * env, jstring p0);
void jthrowC_AccessDeniedException(JNIEnv * env, char* p0);
void jthrowCC_AccessDeniedException(JNIEnv * env, const char* p0);
void jthrow_AccessDeniedException_1(JNIEnv * env, jstring p0, jstring p1, jstring p2);
void jthrowC_AccessDeniedException_1(JNIEnv * env, char* p0, char* p1, char* p2);
void jthrowCC_AccessDeniedException_1(JNIEnv * env, const char* p0, const char* p1, const char* p2);
void jthrow_FileAlreadyExistsException(JNIEnv * env, jstring p0);
void jthrowC_FileAlreadyExistsException(JNIEnv * env, char* p0);
void jthrowCC_FileAlreadyExistsException(JNIEnv * env, const char* p0);
void jthrow_FileAlreadyExistsException_1(JNIEnv * env, jstring p0, jstring p1, jstring p2);
void jthrowC_FileAlreadyExistsException_1(JNIEnv * env, char* p0, char* p1, char* p2);
void jthrowCC_FileAlreadyExistsException_1(JNIEnv * env, const char* p0, const char* p1, const char* p2);
void jthrow_FileSystemLoopException(JNIEnv * env, jstring p0);
void jthrowC_FileSystemLoopException(JNIEnv * env, char* p0);
void jthrowCC_FileSystemLoopException(JNIEnv * env, const char* p0);
void jthrow_InvalidPathException(JNIEnv * env, jstring p0, jstring p1);
void jthrowC_InvalidPathException(JNIEnv * env, char* p0, char* p1);
void jthrowCC_InvalidPathException(JNIEnv * env, const char* p0, const char* p1);
void jthrow_InvalidPathException_1(JNIEnv * env, jstring p0, jstring p1, jint p2);
void jthrowC_InvalidPathException_1(JNIEnv * env, char* p0, char* p1, jint p2);
void jthrowCC_InvalidPathException_1(JNIEnv * env, const char* p0, const char* p1, jint p2);
void jthrow_NotDirectoryException(JNIEnv * env, jstring p0);
void jthrowC_NotDirectoryException(JNIEnv * env, char* p0);
void jthrowCC_NotDirectoryException(JNIEnv * env, const char* p0);
void jthrow_NotLinkException(JNIEnv * env, jstring p0);
void jthrowC_NotLinkException(JNIEnv * env, char* p0);
void jthrowCC_NotLinkException(JNIEnv * env, const char* p0);
void jthrow_NotLinkException_1(JNIEnv * env, jstring p0, jstring p1, jstring p2);
void jthrowC_NotLinkException_1(JNIEnv * env, char* p0, char* p1, char* p2);
void jthrowCC_NotLinkException_1(JNIEnv * env, const char* p0, const char* p1, const char* p2);
void jthrow_ReadOnlyFileSystemException(JNIEnv * env);
void jthrow_NoSuchElementException(JNIEnv * env);
void jthrow_NoSuchElementException_1(JNIEnv * env, jstring p0);
void jthrowC_NoSuchElementException_1(JNIEnv * env, char* p0);
void jthrowCC_NoSuchElementException_1(JNIEnv * env, const char* p0);
