version: '3'

services:

  java-native-utils-test-risc64:
    build:
      context: image
    container_name: java-native-utils-test-risc64
    environment:
      - QEMU=TRUE
      - QARCH=riscv64
    volumes:
      - ../../../:/project
    entrypoint: /usr/bin/env bash /project/JavaNativeUtilsTest/docker/runtest.sh


